use chrono::Utc;
use hmac::{Hmac, Mac};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use crate::ResourceResponse;

fn sign(key: &[u8], value: &str) -> Result<Vec<u8>, String> { let mut mac: Hmac<Sha256> = <Hmac<Sha256> as Mac>::new_from_slice(key).map_err(|e| e.to_string())?; mac.update(value.as_bytes()); Ok(mac.finalize().into_bytes().to_vec()) }
fn query(params: &BTreeMap<String, String>) -> String { params.iter().map(|(key, value)| (crate::rpc_encode(key), crate::rpc_encode(value))).map(|(key, value)| format!("{key}={value}")).collect::<Vec<_>>().join("&") }
async fn request(id: i64, service: &str, region: &str, host: &str, path: &str, params: BTreeMap<String, String>) -> Result<String, String> {
    if crate::account_cloud_type(id)? != "aws" { return Err("当前账号不是 AWS 账号".into()); }
    let (access_key_id, secret) = crate::account_credentials(id)?; let datetime = Utc::now().format("%Y%m%dT%H%M%SZ").to_string(); let date = &datetime[..8]; let query_text = query(&params); let payload_hash = format!("{:x}", Sha256::digest(b"")); let canonical_headers = format!("host:{host}\nx-amz-date:{datetime}\n"); let signed_headers = "host;x-amz-date"; let canonical_request = format!("GET\n{path}\n{query_text}\n{canonical_headers}\n{signed_headers}\n{payload_hash}"); let scope = format!("{date}/{region}/{service}/aws4_request"); let string_to_sign = format!("AWS4-HMAC-SHA256\n{datetime}\n{scope}\n{:x}", Sha256::digest(canonical_request.as_bytes())); let date_key = sign(format!("AWS4{secret}").as_bytes(), date)?; let region_key = sign(&date_key, region)?; let service_key = sign(&region_key, service)?; let signing_key = sign(&service_key, "aws4_request")?; let authorization = format!("AWS4-HMAC-SHA256 Credential={access_key_id}/{scope}, SignedHeaders={signed_headers}, Signature={}", hex::encode(sign(&signing_key, &string_to_sign)?));
    let url = format!("https://{host}{path}{}", if query_text.is_empty() { String::new() } else { format!("?{query_text}") }); let response = reqwest::Client::new().get(url).header("Host", host).header("X-Amz-Date", &datetime).header("Authorization", authorization).timeout(std::time::Duration::from_secs(30)).send().await.map_err(|e| format!("AWS 请求失败: {e}"))?; let status = response.status(); let body = response.text().await.map_err(|e| format!("AWS 返回读取失败: {e}"))?;
    if !status.is_success() { let message = { let value = crate::xml_text(&body, "Message"); if value.is_empty() { crate::xml_text(&body, "Code") } else { value } }; crate::write_api_log(&access_key_id, host, &format!("GET {path}"), &serde_json::json!(params), Some(&serde_json::json!({"body": body})), "失败", Some(&message)); return Err(format!("AWS {status}: {message}")); } crate::write_api_log(&access_key_id, host, &format!("GET {path}"), &serde_json::json!(params), Some(&serde_json::json!({"body": body})), "成功", None); Ok(body)
}

fn regions(id: i64) -> Result<Vec<String>, String> { crate::configured_regions(id, "ap-northeast-1") }
fn instance(item: &str, region: &str) -> Value { json!({"InstanceId": crate::xml_text(item, "instanceId"), "InstanceName": crate::xml_text(item, "instanceId"), "InstanceStatus": crate::xml_text(&crate::xml_text(item, "instanceState"), "name"), "Status": crate::xml_text(&crate::xml_text(item, "instanceState"), "name"), "PublicIpAddress": crate::xml_text(item, "ipAddress"), "PrivateIpAddress": crate::xml_text(item, "privateIpAddress"), "InstanceType": crate::xml_text(item, "instanceType"), "VpcId": crate::xml_text(item, "vpcId"), "_region_id": region, "_raw_xml": item}) }
fn rds(item: &str, region: &str) -> Value { json!({"DBInstanceId": crate::xml_text(item, "DBInstanceIdentifier"), "DBInstanceDescription": crate::xml_text(item, "DBInstanceIdentifier"), "DBInstanceStatus": crate::xml_text(item, "DBInstanceStatus"), "DBInstanceClass": crate::xml_text(item, "DBInstanceClass"), "DBInstanceStorage": crate::xml_text(item, "AllocatedStorage").parse::<i64>().unwrap_or(0), "ConnectionString": crate::xml_text(&crate::xml_text(item, "Endpoint"), "Address"), "Port": crate::xml_text(&crate::xml_text(item, "Endpoint"), "Port"), "Engine": crate::xml_text(item, "Engine"), "EngineVersion": crate::xml_text(item, "EngineVersion"), "CreateTime": crate::xml_text(item, "InstanceCreateTime"), "_region_id": region, "_raw_xml": item}) }
fn redis(item: &str, region: &str) -> Value { json!({"InstanceId": crate::xml_text(item, "CacheClusterId"), "InstanceName": crate::xml_text(item, "CacheClusterId"), "InstanceStatus": crate::xml_text(item, "CacheClusterStatus"), "InstanceType": "Redis", "InstanceClass": crate::xml_text(item, "CacheNodeType"), "Capacity": 0, "ConnectionDomain": crate::xml_text(&crate::xml_text(item, "ConfigurationEndpoint"), "Address"), "Port": crate::xml_text(&crate::xml_text(item, "ConfigurationEndpoint"), "Port"), "EngineVersion": crate::xml_text(item, "EngineVersion"), "NetworkType": crate::xml_text(item, "VpcId"), "_region_id": region, "_raw_xml": item}) }
fn bucket(item: &str) -> Value { let name = crate::xml_text(item, "Name"); json!({"Name": name, "BucketName": name, "Location": "global", "CreationDate": crate::xml_text(item, "CreationDate"), "StorageClass": "STANDARD", "Acl": "private", "ExtranetEndpoint": "-", "IntranetEndpoint": "-", "_region_id": "global"}) }
fn zone(item: &str) -> Value { json!({"DomainName": crate::xml_text(item, "Name").trim_end_matches('.'), "DomainStatus": "ACTIVE", "ZoneId": crate::xml_text(item, "Id"), "RecordCount": crate::xml_text(item, "ResourceRecordSetCount").parse::<i64>().unwrap_or(0), "RegistrationDate": "", "_region_id": "global", "_aws_route53": true}) }

pub(crate) async fn resource_items(id: i64, resource_type: &str) -> ResourceResponse {
    let now = Utc::now().timestamp_millis(); let regions = match regions(id) { Ok(v) => v, Err(e) => return ResourceResponse { resource_type: resource_type.into(), items: vec![], errors: vec![e], fetched_at: now } }; let mut items = Vec::new(); let mut errors = Vec::new();
    if resource_type == "oss" { match request(id, "s3", "us-east-1", "s3.amazonaws.com", "/", BTreeMap::new()).await { Ok(body) => items.extend(crate::xml_blocks(&body, "Bucket").into_iter().map(|item| bucket(&item))), Err(e) => errors.push(e) }; return ResourceResponse { resource_type: resource_type.into(), items, errors, fetched_at: now }; }
    if resource_type == "domain" { match request(id, "route53", "us-east-1", "route53.amazonaws.com", "/2013-04-01/hostedzone", BTreeMap::new()).await { Ok(body) => items.extend(crate::xml_blocks(&body, "HostedZone").into_iter().map(|item| zone(&item))), Err(e) => errors.push(e) }; return ResourceResponse { resource_type: resource_type.into(), items, errors, fetched_at: now }; }
    for region in regions { let result = match resource_type { "ecs" => request(id, "ec2", &region, &format!("ec2.{region}.amazonaws.com"), "/", crate::string_params(&[("Action", "DescribeInstances".into()), ("Version", "2016-11-15".into())])).await.map(|body| crate::xml_blocks(&body, "instancesSet").into_iter().flat_map(|v| crate::xml_blocks(&v, "item")).map(|v| instance(&v, &region)).collect::<Vec<_>>()), "rds" => request(id, "rds", &region, &format!("rds.{region}.amazonaws.com"), "/", crate::string_params(&[("Action", "DescribeDBInstances".into()), ("Version", "2014-10-31".into())])).await.map(|body| crate::xml_blocks(&body, "DBInstances").into_iter().flat_map(|v| crate::xml_blocks(&v, "DBInstance")).map(|v| rds(&v, &region)).collect::<Vec<_>>()), "redis" => request(id, "elasticache", &region, &format!("elasticache.{region}.amazonaws.com"), "/", crate::string_params(&[("Action", "DescribeCacheClusters".into()), ("Version", "2015-02-02".into()), ("ShowCacheNodeInfo", "true".into())])).await.map(|body| crate::xml_blocks(&body, "CacheClusters").into_iter().flat_map(|v| crate::xml_blocks(&v, "CacheCluster")).map(|v| redis(&v, &region)).collect::<Vec<_>>()), _ => return ResourceResponse { resource_type: resource_type.into(), items, errors: vec![format!("AWS 暂未接入 {resource_type} 资源")], fetched_at: now } }; match result { Ok(v) => items.extend(v), Err(e) => errors.push(format!("{region}: {e}")) } }
    ResourceResponse { resource_type: resource_type.into(), items, errors, fetched_at: now }
}

pub(crate) async fn verify_account(id: i64) -> Result<Value, String> {
    let regions = regions(id)?;
    let default_region = regions.first().cloned().ok_or_else(|| "AWS 未配置可用区域".to_string())?;
    request(id, "ec2", &default_region, &format!("ec2.{default_region}.amazonaws.com"), "/", crate::string_params(&[("Action", "DescribeInstances".into()), ("Version", "2016-11-15".into()), ("MaxResults", "5".into())])).await?;
    Ok(json!({"provider":"aws","verified":true,"region_count":regions.len(),"regions":regions,"default_region":default_region}))
}
