use crate::{account_cloud_type, account_credentials, aws_query, aws_sign, configured_regions, string_params, write_api_log, xml_blocks, xml_text, ResourceResponse};
use chrono::Utc;
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;

async fn aws_request(id: i64, service: &str, region: &str, host: &str, path: &str, query: BTreeMap<String, String>) -> Result<String, String> {
    if account_cloud_type(id)? != "aws" { return Err("当前账号不是 AWS 账号".into()); }
    let (access_key_id, access_key_secret) = account_credentials(id)?; let datetime = Utc::now().format("%Y%m%dT%H%M%SZ").to_string(); let date = &datetime[..8]; let query_text = aws_query(&query); let payload_hash = format!("{:x}", Sha256::digest(b"")); let canonical_headers = format!("host:{host}\nx-amz-date:{datetime}\n"); let signed_headers = "host;x-amz-date"; let canonical_request = format!("GET\n{path}\n{query_text}\n{canonical_headers}\n{signed_headers}\n{payload_hash}"); let scope = format!("{date}/{region}/{service}/aws4_request"); let string_to_sign = format!("AWS4-HMAC-SHA256\n{datetime}\n{scope}\n{:x}", Sha256::digest(canonical_request.as_bytes())); let date_key = aws_sign(format!("AWS4{access_key_secret}").as_bytes(), date)?; let region_key = aws_sign(&date_key, region)?; let service_key = aws_sign(&region_key, service)?; let signing_key = aws_sign(&service_key, "aws4_request")?; let authorization = format!("AWS4-HMAC-SHA256 Credential={access_key_id}/{scope}, SignedHeaders={signed_headers}, Signature={}", hex::encode(aws_sign(&signing_key, &string_to_sign)?)); let url = format!("https://{host}{path}{}", if query_text.is_empty() { String::new() } else { format!("?{query_text}") });
    let response = reqwest::Client::new().get(url).header("Host", host).header("X-Amz-Date", &datetime).header("Authorization", authorization).timeout(std::time::Duration::from_secs(30)).send().await.map_err(|error| format!("AWS 请求失败: {error}"))?; let status = response.status(); let body = response.text().await.map_err(|error| format!("AWS 返回读取失败: {error}"))?;
    if !status.is_success() { let message = { let value = xml_text(&body, "Message"); if value.is_empty() { xml_text(&body, "Code") } else { value } }; write_api_log(&access_key_id, host, &format!("GET {path}"), &json!(query), Some(&json!({"body": body})), "失败", Some(&message)); return Err(format!("AWS {status}: {message}")); }
    write_api_log(&access_key_id, host, &format!("GET {path}"), &json!(query), Some(&json!({"body": body})), "成功", None); Ok(body)
}

fn aws_instance(item: &str, region: &str) -> Value { json!({"InstanceId": xml_text(item, "instanceId"), "InstanceName": xml_text(item, "instanceId"), "InstanceStatus": xml_text(&xml_text(item, "instanceState"), "name"), "Status": xml_text(&xml_text(item, "instanceState"), "name"), "PublicIpAddress": xml_text(item, "ipAddress"), "PrivateIpAddress": xml_text(item, "privateIpAddress"), "InstanceType": xml_text(item, "instanceType"), "VpcId": xml_text(item, "vpcId"), "_region_id": region, "_raw_xml": item}) }
fn aws_rds(item: &str, region: &str) -> Value { json!({"DBInstanceId": xml_text(item, "DBInstanceIdentifier"), "DBInstanceDescription": xml_text(item, "DBInstanceIdentifier"), "DBInstanceStatus": xml_text(item, "DBInstanceStatus"), "DBInstanceClass": xml_text(item, "DBInstanceClass"), "DBInstanceStorage": xml_text(item, "AllocatedStorage").parse::<i64>().unwrap_or(0), "ConnectionString": xml_text(&xml_text(item, "Endpoint"), "Address"), "Port": xml_text(&xml_text(item, "Endpoint"), "Port"), "Engine": xml_text(item, "Engine"), "EngineVersion": xml_text(item, "EngineVersion"), "CreateTime": xml_text(item, "InstanceCreateTime"), "_region_id": region, "_raw_xml": item}) }
fn aws_redis(item: &str, region: &str) -> Value { json!({"InstanceId": xml_text(item, "CacheClusterId"), "InstanceName": xml_text(item, "CacheClusterId"), "InstanceStatus": xml_text(item, "CacheClusterStatus"), "InstanceType": "Redis", "InstanceClass": xml_text(item, "CacheNodeType"), "Capacity": 0, "ConnectionDomain": xml_text(&xml_text(item, "ConfigurationEndpoint"), "Address"), "Port": xml_text(&xml_text(item, "ConfigurationEndpoint"), "Port"), "EngineVersion": xml_text(item, "EngineVersion"), "NetworkType": xml_text(item, "VpcId"), "_region_id": region, "_raw_xml": item}) }

pub(crate) async fn resource_items(id: i64, resource_type: &str) -> ResourceResponse {
    let now = Utc::now().timestamp_millis(); let regions = match configured_regions(id, "ap-northeast-1") { Ok(value) => value, Err(error) => return ResourceResponse { resource_type: resource_type.into(), items: vec![], errors: vec![error], fetched_at: now } }; let mut items = Vec::new(); let mut errors = Vec::new();
    if resource_type == "oss" { match aws_request(id, "s3", "us-east-1", "s3.amazonaws.com", "/", BTreeMap::new()).await { Ok(body) => items.extend(xml_blocks(&body, "Bucket").into_iter().map(|bucket| json!({"Name": xml_text(&bucket, "Name"), "BucketName": xml_text(&bucket, "Name"), "Location": "global", "CreationDate": xml_text(&bucket, "CreationDate"), "StorageClass": "STANDARD", "Acl": "private", "ExtranetEndpoint": "-", "IntranetEndpoint": "-", "_region_id": "global"}))), Err(error) => errors.push(error), }; return ResourceResponse { resource_type: resource_type.into(), items, errors, fetched_at: now }; }
    if resource_type == "domain" { match aws_request(id, "route53", "us-east-1", "route53.amazonaws.com", "/2013-04-01/hostedzone", BTreeMap::new()).await { Ok(body) => items.extend(xml_blocks(&body, "HostedZone").into_iter().map(|zone| json!({"DomainName": xml_text(&zone, "Name").trim_end_matches('.'), "DomainStatus": "ACTIVE", "ZoneId": xml_text(&zone, "Id"), "RecordCount": xml_text(&zone, "ResourceRecordSetCount").parse::<i64>().unwrap_or(0), "RegistrationDate": "", "_region_id": "global", "_aws_route53": true}))), Err(error) => errors.push(error), }; return ResourceResponse { resource_type: resource_type.into(), items, errors, fetched_at: now }; }
    for region in regions { let response = match resource_type { "ecs" => aws_request(id, "ec2", &region, &format!("ec2.{region}.amazonaws.com"), "/", string_params(&[("Action", "DescribeInstances".into()), ("Version", "2016-11-15".into())])).await.map(|body| xml_blocks(&body, "instancesSet").into_iter().flat_map(|set| xml_blocks(&set, "item")).map(|item| aws_instance(&item, &region)).collect::<Vec<_>>()), "rds" => aws_request(id, "rds", &region, &format!("rds.{region}.amazonaws.com"), "/", string_params(&[("Action", "DescribeDBInstances".into()), ("Version", "2014-10-31".into())])).await.map(|body| xml_blocks(&body, "DBInstances").into_iter().flat_map(|set| xml_blocks(&set, "DBInstance")).map(|item| aws_rds(&item, &region)).collect::<Vec<_>>()), "redis" => aws_request(id, "elasticache", &region, &format!("elasticache.{region}.amazonaws.com"), "/", string_params(&[("Action", "DescribeCacheClusters".into()), ("Version", "2015-02-02".into()), ("ShowCacheNodeInfo", "true".into())])).await.map(|body| xml_blocks(&body, "CacheClusters").into_iter().flat_map(|set| xml_blocks(&set, "CacheCluster")).map(|item| aws_redis(&item, &region)).collect::<Vec<_>>()), _ => return ResourceResponse { resource_type: resource_type.into(), items, errors: vec![format!("AWS 暂未接入 {resource_type} 资源")], fetched_at: now } }; match response { Ok(values) => items.extend(values), Err(error) => errors.push(format!("{region}: {error}")), } }
    ResourceResponse { resource_type: resource_type.into(), items, errors, fetched_at: now }
}

#[tauri::command]
pub(crate) async fn verify_aws_account(id: i64) -> Result<Value, String> { let regions = configured_regions(id, "ap-northeast-1")?; aws_request(id, "ec2", &regions[0], &format!("ec2.{}.amazonaws.com", regions[0]), "/", string_params(&[("Action", "DescribeInstances".into()), ("Version", "2016-11-15".into()), ("MaxResults", "5".into())])).await?; Ok(json!({"provider":"aws","verified":true,"region_count":regions.len(),"regions":regions,"default_region":configured_regions(id, "ap-northeast-1")?[0]})) }


