use crate::{array_at, configured_regions, rpc_encode, ResourceResponse};
use crate::core::storage::{decrypt_secret, open_db};
use chrono::Utc;
use serde_json::{json, Value};

struct AzureCredentials { client_id: String, client_secret: String, tenant_id: String, subscription_id: String }

fn azure_credentials(id: i64) -> Result<AzureCredentials, String> {
    let conn = open_db()?; let row: (String, String, Option<String>, i64, String) = conn.query_row("SELECT access_key_id,secret_ciphertext,credential_meta,enabled,cloud_type FROM cloud_accounts WHERE id=?1", [id], |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?, row.get(4)?))).map_err(|error| format!("读取云账号失败: {error}"))?;
    if row.3 != 1 { return Err("云账号已停用".into()); } if row.4 != "azure" { return Err("当前账号不是 Microsoft Azure 账号".into()); }
    let meta: Value = serde_json::from_str(row.2.as_deref().unwrap_or("{}")).map_err(|_| "Azure 凭证信息格式无效".to_string())?; let tenant_id = meta.get("tenant_id").and_then(Value::as_str).unwrap_or("").trim().to_string(); let subscription_id = meta.get("subscription_id").and_then(Value::as_str).unwrap_or("").trim().to_string(); if tenant_id.is_empty() || subscription_id.is_empty() { return Err("Azure 账号缺少 Tenant ID 或 Subscription ID".into()); }
    Ok(AzureCredentials { client_id: row.0, client_secret: decrypt_secret(&row.1)?, tenant_id, subscription_id })
}

async fn azure_token(credentials: &AzureCredentials) -> Result<String, String> {
    let response = reqwest::Client::new().post(format!("https://login.microsoftonline.com/{}/oauth2/v2.0/token", rpc_encode(&credentials.tenant_id))).form(&[("client_id", credentials.client_id.as_str()), ("client_secret", credentials.client_secret.as_str()), ("grant_type", "client_credentials"), ("scope", "https://management.azure.com/.default")]).timeout(std::time::Duration::from_secs(30)).send().await.map_err(|error| format!("Azure OAuth 请求失败: {error}"))?; let status = response.status(); let data: Value = response.json().await.map_err(|error| format!("Azure OAuth 返回解析失败: {error}"))?; if !status.is_success() { return Err(data.get("error_description").or_else(|| data.get("error")).and_then(Value::as_str).unwrap_or("Azure OAuth 失败").to_string()); } data.get("access_token").and_then(Value::as_str).map(String::from).ok_or_else(|| "Azure OAuth 未返回 access token".into())
}

async fn azure_resources_raw(credentials: &AzureCredentials) -> Result<Vec<Value>, String> {
    let token = azure_token(credentials).await?; let mut next = format!("https://management.azure.com/subscriptions/{}/resources?api-version=2021-04-01", rpc_encode(&credentials.subscription_id)); let mut values = Vec::new();
    for _ in 0..100 { if next.is_empty() { break; } let response = reqwest::Client::new().get(&next).bearer_auth(&token).timeout(std::time::Duration::from_secs(30)).send().await.map_err(|error| format!("Azure ARM 请求失败: {error}"))?; let status = response.status(); let data: Value = response.json().await.map_err(|error| format!("Azure ARM 返回解析失败: {error}"))?; if !status.is_success() { return Err(data.pointer("/error/message").or_else(|| data.get("message")).and_then(Value::as_str).unwrap_or("Azure ARM 返回错误").to_string()); } values.extend(array_at(&data, &["value"]).into_iter().cloned()); next = data.get("nextLink").and_then(Value::as_str).unwrap_or("").to_string(); }
    Ok(values)
}

fn azure_instance(item: &Value) -> Value { let p = item.get("properties").cloned().unwrap_or(Value::Null); json!({"InstanceId": item.get("id"), "InstanceName": item.get("name"), "InstanceStatus": p.get("provisioningState"), "Status": p.get("provisioningState"), "PublicIpAddress": "", "PrivateIpAddress": "", "InstanceType": p.pointer("/hardwareProfile/vmSize"), "VpcId": "", "_region_id": item.get("location"), "_raw": item}) }
fn azure_rds(item: &Value) -> Value { let p = item.get("properties").cloned().unwrap_or(Value::Null); json!({"DBInstanceId": item.get("id"), "DBInstanceDescription": item.get("name"), "DBInstanceStatus": p.get("state").or_else(|| p.get("provisioningState")), "DBInstanceClass": item.pointer("/sku/name"), "DBInstanceStorage": 0, "ConnectionString": p.get("fullyQualifiedDomainName"), "Port": "", "Engine": "Azure SQL", "EngineVersion": p.get("version"), "CreateTime": "", "_region_id": item.get("location"), "_raw": item}) }
fn azure_redis(item: &Value) -> Value { let p = item.get("properties").cloned().unwrap_or(Value::Null); json!({"InstanceId": item.get("id"), "InstanceName": item.get("name"), "InstanceStatus": p.get("provisioningState"), "InstanceType": "Redis", "InstanceClass": item.pointer("/sku/name"), "Capacity": item.pointer("/sku/capacity").cloned().unwrap_or(json!(0)), "ConnectionDomain": p.get("hostName"), "Port": p.get("sslPort").or_else(|| p.get("port")), "EngineVersion": p.get("redisVersion"), "NetworkType": p.get("subnetId"), "_region_id": item.get("location"), "_raw": item}) }
fn azure_bucket(item: &Value) -> Value { let p = item.get("properties").cloned().unwrap_or(Value::Null); json!({"Name": item.get("name"), "BucketName": item.get("name"), "Location": item.get("location"), "CreationDate": p.get("creationTime"), "StorageClass": item.pointer("/sku/name").cloned().unwrap_or(json!("Standard")), "Acl": if p.get("allowBlobPublicAccess").and_then(Value::as_bool) == Some(true) { "public" } else { "private" }, "ExtranetEndpoint": "-", "IntranetEndpoint": "-", "_region_id": item.get("location"), "_raw": item}) }
fn azure_zone(item: &Value) -> Value { let p = item.get("properties").cloned().unwrap_or(Value::Null); json!({"DomainName": item.get("name"), "DomainStatus": p.get("provisioningState").cloned().unwrap_or(json!("ACTIVE")), "ZoneId": item.get("id"), "RecordCount": p.get("numberOfRecordSets").cloned().unwrap_or(json!(0)), "RegistrationDate": "", "_region_id": item.get("location").cloned().unwrap_or(json!("global")), "_azure_dns": true, "_raw": item}) }

pub(crate) async fn resource_items(id: i64, resource_type: &str) -> ResourceResponse {
    let now = Utc::now().timestamp_millis(); let credentials = match azure_credentials(id) { Ok(value) => value, Err(error) => return ResourceResponse { resource_type: resource_type.into(), items: vec![], errors: vec![error], fetched_at: now } }; let values = match azure_resources_raw(&credentials).await { Ok(value) => value, Err(error) => return ResourceResponse { resource_type: resource_type.into(), items: vec![], errors: vec![error], fetched_at: now } }; let expected = match resource_type { "ecs" => "microsoft.compute/virtualmachines", "rds" => "microsoft.sql/servers", "redis" => "microsoft.cache/redis", "oss" => "microsoft.storage/storageaccounts", "domain" => "microsoft.network/dnszones", _ => return ResourceResponse { resource_type: resource_type.into(), items: vec![], errors: vec![format!("Azure 暂未接入 {resource_type} 资源")], fetched_at: now } }; let items = values.into_iter().filter(|item| item.get("type").and_then(Value::as_str).map(|value| value.eq_ignore_ascii_case(expected)).unwrap_or(false)).map(|item| match resource_type { "ecs" => azure_instance(&item), "rds" => azure_rds(&item), "redis" => azure_redis(&item), "oss" => azure_bucket(&item), "domain" => azure_zone(&item), _ => item }).collect(); ResourceResponse { resource_type: resource_type.into(), items, errors: vec![], fetched_at: now }
}

#[tauri::command]
pub(crate) async fn verify_azure_account(id: i64) -> Result<Value, String> { let credentials = azure_credentials(id)?; let token = azure_token(&credentials).await?; let response = reqwest::Client::new().get(format!("https://management.azure.com/subscriptions/{}?api-version=2022-12-01", rpc_encode(&credentials.subscription_id))).bearer_auth(token).timeout(std::time::Duration::from_secs(30)).send().await.map_err(|error| format!("Azure ARM 请求失败: {error}"))?; if !response.status().is_success() { return Err(format!("Azure 订阅验证失败：{}", response.status())); } let regions = configured_regions(id, "eastasia")?; Ok(json!({"provider":"azure","verified":true,"region_count":regions.len(),"regions":regions,"default_region":configured_regions(id, "eastasia")?[0]})) }

