use chrono::Utc;
use hmac::{Hmac, Mac};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use uuid::Uuid;
use crate::ResourceResponse;

fn sign(key: &[u8], value: &str) -> Result<Vec<u8>, String> { let mut mac: Hmac<Sha256> = <Hmac<Sha256> as Mac>::new_from_slice(key).map_err(|error| error.to_string())?; mac.update(value.as_bytes()); Ok(mac.finalize().into_bytes().to_vec()) }
fn query(params: &BTreeMap<String, String>) -> String { params.iter().map(|(key, value)| (crate::rpc_encode(key), crate::rpc_encode(value))).map(|(key, value)| format!("{key}={value}")).collect::<Vec<_>>().join("&") }
async fn request(id: i64, service: &str, region: &str, path: &str, params: BTreeMap<String, String>) -> Result<Value, String> {
    if crate::account_cloud_type(id)? != "jdcloud" { return Err("当前账号不是京东云账号".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let datetime = Utc::now().format("%Y%m%dT%H%M%SZ").to_string(); let date = &datetime[..8]; let host = if service == "oss" { "oss.jdcloud-api.com".to_string() } else if service == "domainservice" { "domainservice.jdcloud-api.com".to_string() } else { format!("{service}.{region}.jdcloud-api.com") }; let query_text = query(&params); let nonce = Uuid::new_v4().to_string(); let payload_hash = format!("{:x}", Sha256::digest(b"")); let canonical_headers = format!("host:{host}\nx-jdcloud-date:{datetime}\nx-jdcloud-nonce:{nonce}\n"); let signed_headers = "host;x-jdcloud-date;x-jdcloud-nonce"; let canonical_request = format!("GET\n{path}\n{query_text}\n{canonical_headers}\n{signed_headers}\n{payload_hash}"); let scope = format!("{date}/{region}/{service}/jdcloud2_request"); let string_to_sign = format!("JDCLOUD2-HMAC-SHA256\n{datetime}\n{scope}\n{:x}", Sha256::digest(canonical_request.as_bytes())); let date_key = sign(format!("JDCLOUD2{access_key_secret}").as_bytes(), date)?; let region_key = sign(&date_key, region)?; let service_key = sign(&region_key, service)?; let signing_key = sign(&service_key, "jdcloud2_request")?; let authorization = format!("JDCLOUD2-HMAC-SHA256 Credential={access_key_id}/{scope}, SignedHeaders={signed_headers}, Signature={}", hex::encode(sign(&signing_key, &string_to_sign)?));
    let response = reqwest::Client::new().get(format!("https://{host}{path}{}", if query_text.is_empty() { String::new() } else { format!("?{query_text}") })).header("Host", &host).header("X-Jdcloud-Date", &datetime).header("X-Jdcloud-Nonce", nonce).header("Authorization", authorization).timeout(std::time::Duration::from_secs(30)).send().await.map_err(|error| format!("京东云请求失败: {error}"))?; let status = response.status(); let data: Value = response.json().await.map_err(|error| format!("京东云返回解析失败: {error}"))?; if !status.is_success() { let message = data.pointer("/error/message").or_else(|| data.get("message")).or_else(|| data.get("code")).and_then(Value::as_str).unwrap_or("京东云 API 返回错误").to_string(); crate::write_api_log(&access_key_id, &host, &format!("GET {path}"), &json!(params), Some(&data), "失败", Some(&message)); return Err(message); } crate::write_api_log(&access_key_id, &host, &format!("GET {path}"), &json!(params), Some(&data), "成功", None); Ok(data)
}

fn first_string(value: Option<&Value>) -> Value { match value { Some(Value::String(v)) if !v.is_empty() => json!(v), Some(Value::Array(v)) => v.iter().find_map(Value::as_str).map(|v| json!(v)).unwrap_or(json!("")), Some(v) => v.clone(), None => json!("") } }
fn instance(item: &Value, region: &str) -> Value { json!({"InstanceId": item.get("instanceId").or_else(|| item.get("id")), "InstanceName": item.get("name").or_else(|| item.get("instanceId")), "InstanceStatus": item.get("status"), "Status": item.get("status"), "PublicIpAddress": first_string(item.get("elasticIp").or_else(|| item.get("publicIpAddress"))), "PrivateIpAddress": first_string(item.get("privateIpAddress")), "InstanceType": item.get("instanceType").unwrap_or(&json!("")), "VpcId": item.get("vpcId").unwrap_or(&json!("")), "_region_id": region, "_raw": item}) }
fn rds(item: &Value, region: &str) -> Value { json!({"DBInstanceId": item.get("instanceId").or_else(|| item.get("id")), "DBInstanceDescription": item.get("instanceName").or_else(|| item.get("name")).or_else(|| item.get("instanceId")), "DBInstanceStatus": item.get("instanceStatus").or_else(|| item.get("status")), "DBInstanceClass": item.get("instanceClass").or_else(|| item.get("instanceType")), "DBInstanceStorage": item.get("instanceStorageGB").or_else(|| item.get("storageGB")).unwrap_or(&json!(0)), "ConnectionString": item.get("internalDomainName").or_else(|| item.get("connectionString")), "Port": item.get("port"), "Engine": item.get("engine").or_else(|| item.get("engineType")), "EngineVersion": item.get("engineVersion"), "CreateTime": item.get("createTime"), "_region_id": region, "_raw": item}) }
fn redis(item: &Value, region: &str) -> Value { json!({"InstanceId": item.get("cacheInstanceId").or_else(|| item.get("instanceId")).or_else(|| item.get("id")), "InstanceName": item.get("cacheInstanceName").or_else(|| item.get("name")).or_else(|| item.get("cacheInstanceId")), "InstanceStatus": item.get("cacheInstanceStatus").or_else(|| item.get("status")), "InstanceType": "Redis", "InstanceClass": item.get("cacheInstanceClass").or_else(|| item.get("instanceClass")), "Capacity": item.get("cacheInstanceMemoryMB").or_else(|| item.get("memory")).unwrap_or(&json!(0)), "ConnectionDomain": item.get("cacheInstanceDomainName").or_else(|| item.get("connectionDomain")), "Port": item.get("port"), "EngineVersion": item.get("engineVersion"), "NetworkType": item.get("vpcId"), "_region_id": region, "_raw": item}) }
fn bucket(item: &Value, region: &str) -> Value { let name = item.get("name").or_else(|| item.get("bucketName")).or_else(|| item.get("bucket")); json!({"Name": name, "BucketName": name, "Location": item.get("location").or_else(|| item.get("region")).unwrap_or(&json!(region)), "CreationDate": item.get("creationDate").or_else(|| item.get("createTime")), "StorageClass": item.get("storageClass").unwrap_or(&json!("STANDARD")), "Acl": item.get("acl").unwrap_or(&json!("private")), "ExtranetEndpoint": name.and_then(Value::as_str).filter(|v| !v.is_empty()).map(|v| format!("{v}.s3.{region}.jdcloud-oss.com")).unwrap_or_else(|| "-".into()), "IntranetEndpoint": "-", "_region_id": item.get("location").or_else(|| item.get("region")).unwrap_or(&json!(region)), "_raw": item}) }
fn zone(item: &Value, region: &str) -> Value { json!({"DomainName": item.get("domainName").or_else(|| item.get("domain")).or_else(|| item.get("name")), "DomainStatus": item.get("status").unwrap_or(&json!("ACTIVE")), "ZoneId": item.get("id").or_else(|| item.get("domainId")).or_else(|| item.get("domainName")), "RecordCount": item.get("recordCount").or_else(|| item.get("recordNum")).unwrap_or(&json!(0)), "RegistrationDate": item.get("createTime"), "_region_id": region, "_jdcloud_dns": true, "_raw": item}) }
fn swas(item: &Value, region: &str) -> Value { json!({"InstanceId": item.get("instanceId").or_else(|| item.get("id")), "InstanceName": item.get("name").or_else(|| item.get("instanceName")).or_else(|| item.get("instanceId")), "InstanceStatus": item.get("status").or_else(|| item.get("instanceStatus")), "Status": item.get("status").or_else(|| item.get("instanceStatus")), "PublicIpAddress": first_string(item.get("publicIpAddress").or_else(|| item.get("elasticIp")).or_else(|| item.get("publicIp"))), "PrivateIpAddress": first_string(item.get("privateIpAddress").or_else(|| item.get("privateIp"))), "InstanceType": item.get("instanceType").or_else(|| item.get("planName")).or_else(|| item.get("planId")).unwrap_or(&json!("")), "PlanId": item.get("planId").or_else(|| item.get("planName")).unwrap_or(&json!("")), "ImageId": item.get("imageId").or_else(|| item.get("imageName")).unwrap_or(&json!("")), "Cpu": item.get("cpu").or_else(|| item.get("cpuCores")).or_else(|| item.get("vCpu")).unwrap_or(&json!(0)), "Memory": item.get("memory").or_else(|| item.get("memorySize")).or_else(|| item.get("memoryMB")).unwrap_or(&json!(0)), "Bandwidth": item.get("bandwidth").or_else(|| item.get("bandwidthMbps")).unwrap_or(&json!(0)), "SystemDiskSize": item.get("systemDiskSize").or_else(|| item.get("systemDisk")).unwrap_or(&json!(0)), "ExpiredTime": item.get("expiredTime").or_else(|| item.get("expirationTime")).or_else(|| item.get("expireTime")).unwrap_or(&json!("")), "CreateTime": item.get("createTime").or_else(|| item.get("createdTime")).unwrap_or(&json!("")), "VpcId": item.get("vpcId").unwrap_or(&json!("")), "_region_id": region, "_raw": item}) }

pub(crate) async fn resource_items(id: i64, resource_type: &str) -> ResourceResponse {
    let now = Utc::now().timestamp_millis(); let regions = match crate::configured_regions(id, "cn-north-1") { Ok(v) => v, Err(e) => return ResourceResponse { resource_type: resource_type.into(), items: vec![], errors: vec![e], fetched_at: now } }; let mut items = Vec::new(); let mut errors = Vec::new();
    let definition = match resource_type { "ecs" => Some(("vm", "v1", "instances")), "rds" => Some(("rds", "v1", "instances")), "redis" => Some(("redis", "v1", "cacheInstance")), "oss" => Some(("oss", "v1", "buckets")), "domain" => Some(("domainservice", "v2", "domain")), "swas" => Some(("lavm", "v1", "instances")), _ => None };
    let Some((service, version, resource)) = definition else { return ResourceResponse { resource_type: resource_type.into(), items, errors: vec![format!("京东云暂未接入 {resource_type} 资源")], fetched_at: now }; };
    for region in regions { let query = if resource_type == "oss" { BTreeMap::new() } else { crate::string_params(&[("pageNumber", "1".into()), ("pageSize", "100".into())]) }; match request(id, service, &region, &format!("/{version}/regions/{}/{}", crate::rpc_encode(&region), resource), query).await { Ok(data) => { let values = crate::array_at(&data, &["result", "instances"]).into_iter().chain(crate::array_at(&data, &["result", "cacheInstances"])).chain(crate::array_at(&data, &["result", "cacheInstance"])).chain(crate::array_at(&data, &["result", "buckets"])).chain(crate::array_at(&data, &["result", "dataList"])).chain(crate::array_at(&data, &["result", "data"])).chain(crate::array_at(&data, &["buckets"])); for item in values { items.push(match resource_type { "ecs" => instance(item, &region), "rds" => rds(item, &region), "redis" => redis(item, &region), "oss" => bucket(item, &region), "domain" => zone(item, &region), "swas" => swas(item, &region), _ => item.clone() }); } }, Err(e) => errors.push(format!("{region}: {e}")) } }
    ResourceResponse { resource_type: resource_type.into(), items, errors, fetched_at: now }
}

pub(crate) async fn verify_account(id: i64) -> Result<Value, String> {
    let regions = crate::configured_regions(id, "cn-north-1")?; let default_region = regions.first().cloned().ok_or_else(|| "京东云未配置可用区域".to_string())?;
    request(id, "vm", &default_region, &format!("/v1/regions/{}/instances", crate::rpc_encode(&default_region)), crate::string_params(&[("pageNumber", "1".into()), ("pageSize", "1".into())])).await?;
    Ok(json!({"provider":"jdcloud","verified":true,"region_count":regions.len(),"regions":regions,"default_region":default_region}))
}

pub(crate) async fn instance_action(id: i64, region: &str, instance_id: &str, action: &str) -> Result<Value, String> {
    if crate::account_cloud_type(id)? != "jdcloud" { return Err("当前账号不是京东云账号".into()); }
    if region.trim().is_empty() || instance_id.trim().is_empty() { return Err("缺少轻量服务器地域或实例 ID".into()); }
    let path = format!("/v1/regions/{}/instances/{}:{}", crate::rpc_encode(region), crate::rpc_encode(instance_id), action); let (access_key_id, access_key_secret) = crate::account_credentials(id)?;
    let datetime = Utc::now().format("%Y%m%dT%H%M%SZ").to_string(); let date = &datetime[..8]; let host = format!("lavm.{region}.jdcloud-api.com"); let nonce = Uuid::new_v4().to_string(); let payload_hash = format!("{:x}", Sha256::digest(b"")); let canonical_headers = format!("host:{host}\nx-jdcloud-date:{datetime}\nx-jdcloud-nonce:{nonce}\n"); let signed_headers = "host;x-jdcloud-date;x-jdcloud-nonce"; let canonical_request = format!("POST\n{path}\n\n{canonical_headers}\n{signed_headers}\n{payload_hash}"); let scope = format!("{date}/{region}/lavm/jdcloud2_request"); let string_to_sign = format!("JDCLOUD2-HMAC-SHA256\n{datetime}\n{scope}\n{:x}", Sha256::digest(canonical_request.as_bytes())); let date_key = sign(format!("JDCLOUD2{access_key_secret}").as_bytes(), date)?; let region_key = sign(&date_key, region)?; let service_key = sign(&region_key, "lavm")?; let signing_key = sign(&service_key, "jdcloud2_request")?; let authorization = format!("JDCLOUD2-HMAC-SHA256 Credential={access_key_id}/{scope}, SignedHeaders={signed_headers}, Signature={}", hex::encode(sign(&signing_key, &string_to_sign)?));
    let response = reqwest::Client::new().post(format!("https://{host}{path}")).header("Host", &host).header("X-Jdcloud-Date", &datetime).header("X-Jdcloud-Nonce", nonce).header("Authorization", authorization).timeout(std::time::Duration::from_secs(30)).send().await.map_err(|error| format!("京东云请求失败: {error}"))?; let status = response.status(); let data: Value = response.json().await.map_err(|error| format!("京东云返回解析失败: {error}"))?; if !status.is_success() { let message = data.pointer("/error/message").or_else(|| data.get("message")).or_else(|| data.get("code")).and_then(Value::as_str).unwrap_or("京东云 API 返回错误").to_string(); crate::write_api_log(&access_key_id, &host, &format!("POST {path}"), &json!({"action":action}), Some(&data), "失败", Some(&message)); return Err(message); } crate::write_api_log(&access_key_id, &host, &format!("POST {path}"), &json!({"action":action}), Some(&data), "成功", None); Ok(data)
}

async fn firewall_mutation(id: i64, region: &str, method: reqwest::Method, path: &str, payload: Value) -> Result<Value, String> {
    if crate::account_cloud_type(id)? != "jdcloud" { return Err("当前账号不是京东云账号".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?;
    let datetime = Utc::now().format("%Y%m%dT%H%M%SZ").to_string(); let date = &datetime[..8]; let host = format!("lavm.{region}.jdcloud-api.com"); let nonce = Uuid::new_v4().to_string();
    let body = serde_json::to_string(&payload).map_err(|error| error.to_string())?; let payload_hash = format!("{:x}", Sha256::digest(body.as_bytes())); let canonical_headers = format!("content-type:application/json\nhost:{host}\nx-jdcloud-date:{datetime}\nx-jdcloud-nonce:{nonce}\n"); let signed_headers = "content-type;host;x-jdcloud-date;x-jdcloud-nonce";
    let canonical_request = format!("{}\n{path}\n\n{canonical_headers}\n{signed_headers}\n{payload_hash}", method.as_str()); let scope = format!("{date}/{region}/lavm/jdcloud2_request"); let string_to_sign = format!("JDCLOUD2-HMAC-SHA256\n{datetime}\n{scope}\n{:x}", Sha256::digest(canonical_request.as_bytes())); let date_key = sign(format!("JDCLOUD2{access_key_secret}").as_bytes(), date)?; let region_key = sign(&date_key, region)?; let service_key = sign(&region_key, "lavm")?; let signing_key = sign(&service_key, "jdcloud2_request")?; let authorization = format!("JDCLOUD2-HMAC-SHA256 Credential={access_key_id}/{scope}, SignedHeaders={signed_headers}, Signature={}", hex::encode(sign(&signing_key, &string_to_sign)?));
    let response = reqwest::Client::new().request(method.clone(), format!("https://{host}{path}")).header("Host", &host).header("Content-Type", "application/json").header("X-Jdcloud-Date", &datetime).header("X-Jdcloud-Nonce", nonce).header("Authorization", authorization).body(body).timeout(std::time::Duration::from_secs(30)).send().await.map_err(|error| format!("京东云请求失败: {error}"))?; let status = response.status(); let data: Value = response.json().await.map_err(|error| format!("京东云返回解析失败: {error}"))?; let operation = format!("{} {path}", method.as_str());
    if !status.is_success() { let message = data.pointer("/error/message").or_else(|| data.get("message")).or_else(|| data.get("code")).and_then(Value::as_str).unwrap_or("京东云防火墙 API 返回错误").to_string(); crate::write_api_log(&access_key_id, &host, &operation, &payload, Some(&data), "失败", Some(&message)); return Err(message); }
    crate::write_api_log(&access_key_id, &host, &operation, &payload, Some(&data), "成功", None); Ok(data)
}

pub(crate) async fn list_firewall_rules(id: i64, region: &str, instance_id: &str) -> Result<Value, String> {
    let result = request(id, "lavm", region, &format!("/v1/regions/{}/firewallRule", crate::rpc_encode(region)), crate::string_params(&[("instanceId", instance_id.to_string()), ("pageSize", "100".into()), ("pageNumber", "1".into())])).await?;
    let rules = crate::array_at(&result, &["result", "firewallRules"]).into_iter().map(|rule| json!({"RuleId": rule.get("ruleId").cloned().unwrap_or(json!("")), "IpProtocol": rule.get("ruleProtocol").cloned().unwrap_or(json!("")), "PortRange": rule.get("port").cloned().unwrap_or(json!("")), "SourceCidrIp": rule.get("sourceAddress").cloned().unwrap_or(json!("")), "Policy": "accept", "Description": rule.get("remark").cloned().unwrap_or(json!(""))})).collect::<Vec<_>>();
    Ok(json!({"rules": rules}))
}

pub(crate) async fn create_firewall_rule(id: i64, region: &str, instance_id: &str, protocol: &str, port: &str, source: &str, remark: &str) -> Result<Value, String> {
    firewall_mutation(id, region, reqwest::Method::POST, &format!("/v1/regions/{}/firewallRule", crate::rpc_encode(region)), json!({"instanceId": instance_id, "sourceAddress": source, "ruleProtocol": protocol.to_ascii_uppercase(), "port": port, "remark": remark, "clientToken": Uuid::new_v4().to_string(), "regionId": region})).await
}

pub(crate) async fn delete_firewall_rule(id: i64, region: &str, instance_id: &str, rule_id: &str) -> Result<Value, String> {
    firewall_mutation(id, region, reqwest::Method::DELETE, &format!("/v1/regions/{}/firewallRule", crate::rpc_encode(region)), json!({"instanceId": instance_id, "ruleId": rule_id, "regionId": region})).await
}
