use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use chrono::Utc;
use hmac::{Hmac, Mac};
use serde_json::{json, Value};
use sha1::Sha1;
use sha2::Sha256;
use crate::ResourceResponse;

fn query(params: &std::collections::BTreeMap<String, String>) -> String { params.iter().map(|(key, value)| (crate::rpc_encode(key), crate::rpc_encode(value))).map(|(key, value)| format!("{key}={value}")).collect::<Vec<_>>().join("&") }
async fn request(id: i64, service: &str, region: &str, action: &str, version: &str, mut params: std::collections::BTreeMap<String, String>) -> Result<Value, String> {
    if crate::account_cloud_type(id)? != "ksyun" { return Err("当前账号不是金山云账号".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let host = format!("{service}.{region}.api.ksyun.com"); params.insert("Action".into(), action.into()); params.insert("Version".into(), version.into()); params.insert("AccessKeyId".into(), access_key_id.clone()); params.insert("SignatureMethod".into(), "HMAC-SHA256".into()); params.insert("SignatureVersion".into(), "1.0".into()); params.insert("Timestamp".into(), Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string()); let canonical = query(&params); let mut mac: Hmac<Sha256> = <Hmac<Sha256> as Mac>::new_from_slice(access_key_secret.as_bytes()).map_err(|error| error.to_string())?; mac.update(format!("GET\n{host}\n/\n{canonical}").as_bytes()); params.insert("Signature".into(), B64.encode(mac.finalize().into_bytes())); let query_text = query(&params); let response = reqwest::Client::new().get(format!("https://{host}/?{query_text}")).timeout(std::time::Duration::from_secs(30)).send().await.map_err(|error| format!("金山云请求失败: {error}"))?; let status = response.status(); let data: Value = response.json().await.map_err(|error| format!("金山云返回解析失败: {error}"))?; if !status.is_success() || data.get("Error").is_some() { let message = data.pointer("/Error/Message").or_else(|| data.get("Message")).and_then(Value::as_str).unwrap_or("金山云 API 返回错误").to_string(); crate::write_api_log(&access_key_id, &host, action, &json!(params), Some(&data), "失败", Some(&message)); return Err(message); } crate::write_api_log(&access_key_id, &host, action, &json!(params), Some(&data), "成功", None); Ok(data)
}

fn instance(item: &Value, region: &str) -> Value { json!({"InstanceId": item.get("InstanceId"), "InstanceName": item.get("InstanceName").or_else(|| item.get("InstanceId")), "InstanceStatus": item.pointer("/InstanceState/Name").or_else(|| item.get("InstanceState")), "Status": item.pointer("/InstanceState/Name").or_else(|| item.get("InstanceState")), "PublicIpAddress": item.get("PublicIpAddress").unwrap_or(&json!("")), "PrivateIpAddress": item.pointer("/NetworkInterfaces/0/PrivateIpAddress").unwrap_or(&json!("")), "InstanceType": item.get("InstanceType").unwrap_or(&json!("")), "VpcId": item.get("VpcId").unwrap_or(&json!("")), "_region_id": region, "_raw": item}) }
fn rds(item: &Value, region: &str) -> Value { json!({"DBInstanceId": item.get("DBInstanceIdentifier"), "DBInstanceDescription": item.get("DBInstanceName").or_else(|| item.get("DBInstanceIdentifier")), "DBInstanceStatus": item.get("DBInstanceStatus"), "DBInstanceClass": item.pointer("/DBInstanceClass/Id").or_else(|| item.get("DBInstanceClass")).unwrap_or(&json!("")), "DBInstanceStorage": item.pointer("/DBInstanceClass/Disk").or_else(|| item.get("Storage")).unwrap_or(&json!(0)), "ConnectionString": item.get("Vip").or_else(|| item.get("VipAddress")).unwrap_or(&json!("")), "Port": item.get("Port").unwrap_or(&json!("")), "Engine": item.get("Engine").unwrap_or(&json!("")), "EngineVersion": item.get("EngineVersion").unwrap_or(&json!("")), "CreateTime": item.get("InstanceCreateTime").unwrap_or(&json!("")), "_region_id": region, "_raw": item}) }
fn redis(item: &Value, region: &str) -> Value { json!({"InstanceId": item.get("CacheId").or_else(|| item.get("CacheClusterId")).or_else(|| item.get("InstanceId")), "InstanceName": item.get("Name").or_else(|| item.get("CacheName")).or_else(|| item.get("CacheClusterName")).or_else(|| item.get("CacheId")), "InstanceStatus": item.get("Status").or_else(|| item.get("CacheStatus")).or_else(|| item.get("CacheClusterStatus")), "InstanceType": "Redis", "InstanceClass": item.get("CacheNodeType").or_else(|| item.get("InstanceClass")).or_else(|| item.get("Type")).unwrap_or(&json!("")), "Capacity": item.get("Capacity").or_else(|| item.get("MemorySize")).unwrap_or(&json!(0)), "ConnectionDomain": item.get("Vip").or_else(|| item.get("Host")).or_else(|| item.get("Endpoint")).unwrap_or(&json!("")), "Port": item.get("Port").unwrap_or(&json!("")), "EngineVersion": item.get("EngineVersion").or_else(|| item.get("RedisVersion")).unwrap_or(&json!("")), "NetworkType": item.get("VpcId").unwrap_or(&json!("")), "_region_id": region, "_raw": item}) }

fn xml_text(body: &str, tag: &str) -> String { let open = format!("<{tag}>"); let close = format!("</{tag}>"); body.find(&open).and_then(|start| body[start + open.len()..].find(&close).map(|end| body[start + open.len()..start + open.len() + end].to_string())).unwrap_or_default() }
fn xml_blocks(body: &str, tag: &str) -> Vec<String> { let open = format!("<{tag}>"); let close = format!("</{tag}>"); let mut values = Vec::new(); let mut rest = body; while let Some(start) = rest.find(&open) { let chunk = &rest[start + open.len()..]; let Some(end) = chunk.find(&close) else { break }; values.push(chunk[..end].to_string()); rest = &chunk[end + close.len()..]; } values }

async fn buckets(id: i64) -> Result<Vec<Value>, String> {
    if crate::account_cloud_type(id)? != "ksyun" { return Err("当前账号不是金山云账号".into()); }
    let (access_key_id, secret) = crate::account_credentials(id)?; let host = "kss.ksyun.com"; let date = Utc::now().format("%a, %d %b %Y %H:%M:%S GMT").to_string(); let mut mac: Hmac<Sha1> = <Hmac<Sha1> as Mac>::new_from_slice(secret.as_bytes()).map_err(|e| e.to_string())?; mac.update(format!("GET\n\n\n{date}\n/").as_bytes());
    let response = reqwest::Client::new().get(format!("https://{host}/")).header("Date", &date).header("Authorization", format!("KSS {access_key_id}:{}", B64.encode(mac.finalize().into_bytes()))).timeout(std::time::Duration::from_secs(30)).send().await.map_err(|e| format!("KS3 请求失败: {e}"))?; let status = response.status(); let body = response.text().await.map_err(|e| format!("KS3 返回读取失败: {e}"))?;
    if !status.is_success() { let message = xml_text(&body, "Message"); return Err(if message.is_empty() { format!("KS3 {status}") } else { message }); }
    Ok(xml_blocks(&body, "Bucket").into_iter().filter_map(|item| { let name = xml_text(&item, "Name"); if name.is_empty() { None } else { let location = xml_text(&item, "Location"); Some(json!({"Name": name, "BucketName": name, "Location": location, "CreationDate": xml_text(&item, "CreationDate"), "StorageClass": "STANDARD", "Acl": "private", "ExtranetEndpoint": format!("{name}.{host}"), "IntranetEndpoint": "-", "_region_id": location})) } }).collect())
}
pub(crate) async fn resource_items(id: i64, resource_type: &str) -> ResourceResponse {
    let now = Utc::now().timestamp_millis(); if resource_type == "oss" { return match buckets(id).await { Ok(items) => ResourceResponse { resource_type: resource_type.into(), items, errors: vec![], fetched_at: now }, Err(e) => ResourceResponse { resource_type: resource_type.into(), items: vec![], errors: vec![e], fetched_at: now } }; }
    let definition = match resource_type { "ecs" => Some(("kec", "DescribeInstances", "2016-03-04", "InstancesSet")), "rds" => Some(("krds", "DescribeDBInstances", "2016-07-01", "Data")), "redis" => Some(("kcs", "DescribeCacheClusters", "2016-07-01", "CacheClusters")), _ => None }; let Some((service, action, version, key)) = definition else { return ResourceResponse { resource_type: resource_type.into(), items: vec![], errors: vec![format!("金山云暂未接入 {resource_type} 资源")], fetched_at: now }; };
    let regions = match crate::configured_regions(id, "cn-beijing-6") { Ok(v) => v, Err(e) => return ResourceResponse { resource_type: resource_type.into(), items: vec![], errors: vec![e], fetched_at: now } }; let mut items = Vec::new(); let mut errors = Vec::new();
    for region in regions { let query = if resource_type == "ecs" { crate::string_params(&[("MaxResults", "100".into())]) } else { crate::string_params(&[("MaxRecords", "100".into())]) }; match request(id, service, &region, action, version, query).await { Ok(data) => { let values = if key == "Data" { crate::array_at(&data, &["Data", "Instances"]) } else if key == "CacheClusters" { let first = crate::array_at(&data, &["CacheClusters"]); if first.is_empty() { crate::array_at(&data, &["Data", "CacheClusters"]) } else { first } } else { let first = crate::array_at(&data, &["InstancesSet"]); if first.is_empty() { crate::array_at(&data, &["Instances"]) } else { first } }; for item in values { items.push(match resource_type { "ecs" => instance(item, &region), "rds" => rds(item, &region), "redis" => redis(item, &region), _ => item.clone() }); } }, Err(e) => errors.push(format!("{region}: {e}")) } }
    ResourceResponse { resource_type: resource_type.into(), items, errors, fetched_at: now }
}

pub(crate) async fn verify_account(id: i64) -> Result<Value, String> { let regions = crate::configured_regions(id, "cn_beijing_6")?; let default_region = regions.first().cloned().ok_or_else(|| "金山云未配置可用区域".to_string())?; request(id, "kec", &default_region, "DescribeInstances", "2016-03-04", crate::string_params(&[("MaxResults", "1".into())])).await?; Ok(json!({"provider":"ksyun","verified":true,"region_count":regions.len(),"regions":regions,"default_region":default_region})) }
