use chrono::Utc;
use base64::{engine::general_purpose::STANDARD as B64, Engine as _};
use hmac::{Hmac, Mac};
use serde_json::{json, Value};
use sha2::Sha256;
use std::collections::BTreeMap;
use crate::ResourceResponse;

fn query(params: &BTreeMap<String, String>) -> String { params.iter().map(|(key, value)| (crate::rpc_encode(key), crate::rpc_encode(value))).map(|(key, value)| format!("{key}={value}")).collect::<Vec<_>>().join("&") }
async fn request(id: i64, action: &str, zone: &str, mut params: BTreeMap<String, String>) -> Result<Value, String> {
    if crate::account_cloud_type(id)? != "qingcloud" { return Err("当前账号不是青云 QingCloud 账号".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?; params.insert("action".into(), action.into()); params.insert("zone".into(), zone.into()); params.insert("access_key_id".into(), access_key_id.clone()); params.insert("time_stamp".into(), Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string()); params.insert("version".into(), "1".into()); params.insert("signature_method".into(), "HmacSHA256".into()); params.insert("signature_version".into(), "1".into()); let canonical = query(&params); let mut mac: Hmac<Sha256> = <Hmac<Sha256> as Mac>::new_from_slice(access_key_secret.as_bytes()).map_err(|error| error.to_string())?; mac.update(format!("GET\n/iaas/\n{canonical}").as_bytes()); params.insert("signature".into(), B64.encode(mac.finalize().into_bytes())); let query_text = query(&params); let response = reqwest::Client::new().get(format!("https://api.qingcloud.com/iaas/?{query_text}")).timeout(std::time::Duration::from_secs(30)).send().await.map_err(|error| format!("青云请求失败: {error}"))?; let status = response.status(); let data: Value = response.json().await.map_err(|error| format!("青云返回解析失败: {error}"))?; if !status.is_success() || data.get("ret_code").and_then(Value::as_i64).unwrap_or(0) != 0 { let message = data.get("message").or_else(|| data.get("ret_message")).and_then(Value::as_str).unwrap_or("青云 API 返回错误").to_string(); crate::write_api_log(&access_key_id, "api.qingcloud.com", action, &json!(params), Some(&data), "失败", Some(&message)); return Err(message); } crate::write_api_log(&access_key_id, "api.qingcloud.com", action, &json!(params), Some(&data), "成功", None); Ok(data)
}

async fn buckets(id: i64) -> Result<Vec<Value>, String> { if crate::account_cloud_type(id)? != "qingcloud" { return Err("当前账号不是青云 QingCloud 账号".into()); } let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let date = Utc::now().format("%a, %d %b %Y %H:%M:%S GMT").to_string(); let mut mac: Hmac<Sha256> = <Hmac<Sha256> as Mac>::new_from_slice(access_key_secret.as_bytes()).map_err(|error| error.to_string())?; mac.update(format!("GET\n\n\n{date}\n/").as_bytes()); let response = reqwest::Client::new().get("https://qingstor.com/").header("Date", &date).header("Authorization", format!("QS {access_key_id}:{}", B64.encode(mac.finalize().into_bytes()))).timeout(std::time::Duration::from_secs(30)).send().await.map_err(|error| format!("QingStor 请求失败: {error}"))?; let status = response.status(); let data: Value = response.json().await.map_err(|error| format!("QingStor 返回解析失败: {error}"))?; if !status.is_success() { let message = data.get("message").and_then(Value::as_str).unwrap_or("QingStor API 返回错误").to_string(); crate::write_api_log(&access_key_id, "qingstor.com", "ListBuckets", &json!({}), Some(&data), "失败", Some(&message)); return Err(message); } let values = crate::array_at(&data, &["buckets"]).into_iter().map(|bucket| json!({"Name":bucket.get("name"),"BucketName":bucket.get("name"),"Location":bucket.get("location").unwrap_or(&json!("")),"CreationDate":bucket.get("created").unwrap_or(&json!("")),"StorageClass":"STANDARD","Acl":"private","ExtranetEndpoint":crate::value_first_string(bucket.get("urls")),"IntranetEndpoint":"-","_region_id":bucket.get("location").unwrap_or(&json!(""))})).collect::<Vec<_>>(); crate::write_api_log(&access_key_id, "qingstor.com", "ListBuckets", &json!({}), Some(&json!({"count":values.len()})), "成功", None); Ok(values) }

fn instance(item: &Value, zone: &str) -> Value { let vxnets = item.get("vxnets").and_then(Value::as_array); let public = vxnets.and_then(|items| items.iter().flat_map(|v| v.get("eips").and_then(Value::as_array).into_iter().flatten()).next()).cloned().unwrap_or(json!("")); let private = vxnets.and_then(|items| items.iter().flat_map(|v| v.get("private_ips").and_then(Value::as_array).into_iter().flatten()).next()).cloned().unwrap_or(json!("")); json!({"InstanceId": item.get("instance_id"), "InstanceName": item.get("instance_name").or_else(|| item.get("instance_id")), "InstanceStatus": item.get("status"), "Status": item.get("status"), "PublicIpAddress": public, "PrivateIpAddress": private, "InstanceType": item.get("instance_type").unwrap_or(&json!("")), "VpcId": item.get("vpc_id").unwrap_or(&json!("")), "_region_id": zone, "_raw": item}) }
fn rds(item: &Value, zone: &str) -> Value { json!({"DBInstanceId": item.get("rdb_id").or_else(|| item.get("rdb")), "DBInstanceDescription": item.get("rdb_name").or_else(|| item.get("rdb_id")).or_else(|| item.get("rdb")), "DBInstanceStatus": item.get("status"), "DBInstanceClass": item.get("rdb_type").or_else(|| item.get("rdb_class")).unwrap_or(&json!("")), "DBInstanceStorage": item.get("storage_size").or_else(|| item.get("storage")).unwrap_or(&json!(0)), "ConnectionString": crate::value_first_string(item.get("vips").or_else(|| item.get("private_ips")).or_else(|| item.get("endpoint"))), "Port": item.get("port").unwrap_or(&json!("")), "Engine": item.get("rdb_engine").unwrap_or(&json!("")), "EngineVersion": item.get("engine_version").unwrap_or(&json!("")), "CreateTime": item.get("create_time").unwrap_or(&json!("")), "_region_id": zone, "_raw": item}) }
fn redis(item: &Value, zone: &str) -> Value { json!({"InstanceId": item.get("cache_id").or_else(|| item.get("cache")), "InstanceName": item.get("cache_name").or_else(|| item.get("cache_id")).or_else(|| item.get("cache")), "InstanceStatus": item.get("status"), "InstanceType": item.get("cache_type").unwrap_or(&json!("Redis")), "InstanceClass": item.get("cache_class").unwrap_or(&json!("")), "Capacity": item.get("cache_size").or_else(|| item.get("memory_size")).unwrap_or(&json!(0)), "ConnectionDomain": crate::value_first_string(item.get("vips").or_else(|| item.get("private_ips")).or_else(|| item.get("endpoint"))), "Port": item.get("port").unwrap_or(&json!("")), "EngineVersion": item.get("cache_version").unwrap_or(&json!("")), "NetworkType": item.get("vxnet_id").or_else(|| item.get("vxnet")).unwrap_or(&json!("")), "_region_id": zone, "_raw": item}) }
fn dns_alias(item: &Value, zone: &str) -> Value { json!({"DomainName": item.get("domain_name").or_else(|| item.get("dns_alias")).or_else(|| item.get("dns_alias_id")), "DomainStatus": item.get("status").unwrap_or(&json!("ACTIVE")), "ZoneId": item.get("dns_alias_id").or_else(|| item.get("dns_alias")).or_else(|| item.get("domain_name")), "RecordCount": 0, "RegistrationDate": item.get("create_time").unwrap_or(&json!("")), "_region_id": zone, "_qingcloud_dns_alias": true, "_raw": item}) }

pub(crate) async fn resource_items(id: i64, resource_type: &str) -> ResourceResponse {
    let now = Utc::now().timestamp_millis(); if resource_type == "oss" { return match buckets(id).await { Ok(items) => ResourceResponse { resource_type: resource_type.into(), items, errors: vec![], fetched_at: now }, Err(e) => ResourceResponse { resource_type: resource_type.into(), items: vec![], errors: vec![e], fetched_at: now } }; }
    let definition = match resource_type { "ecs" => Some(("DescribeInstances", "instance_set")), "rds" => Some(("DescribeRDBs", "rdb_set")), "redis" => Some(("DescribeCaches", "cache_set")), "domain" => Some(("DescribeDNSAliases", "dns_alias_set")), _ => None }; let Some((action, key)) = definition else { return ResourceResponse { resource_type: resource_type.into(), items: vec![], errors: vec![format!("青云 QingCloud 暂未接入 {resource_type} 资源")], fetched_at: now }; };
    let zones = match crate::configured_regions(id, "pek3a") { Ok(v) => v, Err(e) => return ResourceResponse { resource_type: resource_type.into(), items: vec![], errors: vec![e], fetched_at: now } }; let mut items = Vec::new(); let mut errors = Vec::new();
    for zone in zones { match request(id, action, &zone, crate::string_params(&[("limit", "100".into())])).await { Ok(data) => for item in crate::array_at(&data, &[key]) { items.push(match resource_type { "ecs" => instance(item, &zone), "rds" => rds(item, &zone), "redis" => redis(item, &zone), "domain" => dns_alias(item, &zone), _ => item.clone() }); }, Err(e) => errors.push(format!("{zone}: {e}")) } }
    ResourceResponse { resource_type: resource_type.into(), items, errors, fetched_at: now }
}

pub(crate) async fn verify_account(id: i64) -> Result<Value, String> { let zones = crate::configured_regions(id, "pek3a")?; let default_zone = zones.first().cloned().ok_or_else(|| "青云未配置可用区域".to_string())?; request(id, "DescribeInstances", &default_zone, crate::string_params(&[("limit", "1".into())])).await?; Ok(json!({"provider":"qingcloud","verified":true,"region_count":zones.len(),"regions":zones,"default_region":default_zone})) }
