use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256};
use sha1::Sha1;
use serde_json::Value;
use chrono::Utc;
use serde_json::json;
use std::collections::BTreeMap;

use crate::ResourceResponse;

fn xml_text(body: &str, tag: &str) -> String { let open = format!("<{tag}>"); let close = format!("</{tag}>"); body.find(&open).and_then(|start| body[start + open.len()..].find(&close).map(|end| body[start + open.len()..start + open.len() + end].to_string())).unwrap_or_default() }
fn xml_blocks(body: &str, tag: &str) -> Vec<String> { let open = format!("<{tag}>"); let close = format!("</{tag}>"); let mut values = Vec::new(); let mut rest = body; while let Some(start) = rest.find(&open) { let chunk = &rest[start + open.len()..]; let Some(end) = chunk.find(&close) else { break }; values.push(chunk[..end].to_string()); rest = &chunk[end + close.len()..]; } values }
fn cos_authorization(access_key_id: &str, access_key_secret: &str, host: &str) -> Result<String, String> { let start = Utc::now().timestamp() - 1; let sign_time = format!("{start};{}", start + 900); let canonical_request = format!("get\n/\n\n\nhost={host}\n"); let mut key_mac: Hmac<Sha1> = <Hmac<Sha1> as Mac>::new_from_slice(access_key_secret.as_bytes()).map_err(|error| error.to_string())?; key_mac.update(sign_time.as_bytes()); let sign_key = hex::encode(key_mac.finalize().into_bytes()); let string_to_sign = format!("sha1\n{sign_time}\n{:x}\n", Sha1::digest(canonical_request.as_bytes())); let mut sign_mac: Hmac<Sha1> = <Hmac<Sha1> as Mac>::new_from_slice(sign_key.as_bytes()).map_err(|error| error.to_string())?; sign_mac.update(string_to_sign.as_bytes()); Ok(format!("q-sign-algorithm=sha1&q-ak={}&q-sign-time={sign_time}&q-key-time={sign_time}&q-header-list=host&q-url-param-list=&q-signature={}", crate::rpc_encode(access_key_id), hex::encode(sign_mac.finalize().into_bytes()))) }
async fn cos_request(bucket: &str, location: &str, access_key_id: &str, access_key_secret: &str) -> Result<String, String> { let host = if bucket.is_empty() { "service.cos.myqcloud.com".to_string() } else { format!("{bucket}.cos.{location}.myqcloud.com") }; let authorization = cos_authorization(access_key_id, access_key_secret, &host)?; let response = reqwest::Client::new().get(format!("https://{host}/")).header("Host", &host).header("Authorization", authorization).timeout(std::time::Duration::from_secs(25)).send().await.map_err(|error| format!("COS 请求失败: {error}"))?; let status = response.status(); let body = response.text().await.map_err(|error| format!("COS 返回读取失败: {error}"))?; if !status.is_success() { let message = xml_text(&body, "Message"); return Err(format!("COS 返回错误（{status}）：{}", if message.is_empty() { xml_text(&body, "Code") } else { message })); } Ok(body) }
async fn buckets(access_key_id: &str, access_key_secret: &str) -> Result<Vec<Value>, String> { let body = cos_request("", "", access_key_id, access_key_secret).await?; Ok(xml_blocks(&body, "Bucket").into_iter().map(|item| { let name = xml_text(&item, "Name"); let location = xml_text(&item, "Location"); json!({"Name":name,"Location":location,"CreationDate":xml_text(&item,"CreationDate"),"StorageClass":"Standard","ExtranetEndpoint":format!("{}.cos.{}.myqcloud.com",name,location),"IntranetEndpoint":"-","Acl":"private"}) }).filter(|item| item.get("Name").and_then(Value::as_str).is_some_and(|name| !name.is_empty())).collect()) }

pub(crate) async fn request(service: &str, version: &str, action: &str, payload: Value, region: Option<&str>, access_key_id: &str, access_key_secret: &str) -> Result<Value, String> {
    let host = format!("{service}.tencentcloudapi.com");
    let timestamp = Utc::now().timestamp();
    let date = Utc::now().format("%Y-%m-%d").to_string();
    let body = serde_json::to_string(&payload).map_err(|error| format!("腾讯云请求序列化失败: {error}"))?;
    let payload_hash = format!("{:x}", Sha256::digest(body.as_bytes()));
    let canonical_headers = format!("content-type:application/json; charset=utf-8\nhost:{host}\n");
    let signed_headers = "content-type;host";
    let canonical_request = format!("POST\n/\n\n{canonical_headers}\n{signed_headers}\n{payload_hash}");
    let credential_scope = format!("{date}/{service}/tc3_request");
    let string_to_sign = format!("TC3-HMAC-SHA256\n{timestamp}\n{credential_scope}\n{:x}", Sha256::digest(canonical_request.as_bytes()));
    let sign = |key: &[u8], value: &str| -> Result<Vec<u8>, String> {
        let mut mac: Hmac<Sha256> = <Hmac<Sha256> as Mac>::new_from_slice(key).map_err(|error| error.to_string())?;
        mac.update(value.as_bytes());
        Ok(mac.finalize().into_bytes().to_vec())
    };
    let secret_date = sign(format!("TC3{access_key_secret}").as_bytes(), &date)?;
    let secret_service = sign(&secret_date, service)?;
    let secret_signing = sign(&secret_service, "tc3_request")?;
    let signature = hex::encode(sign(&secret_signing, &string_to_sign)?);
    let authorization = format!("TC3-HMAC-SHA256 Credential={access_key_id}/{credential_scope}, SignedHeaders={signed_headers}, Signature={signature}");
    let mut request = reqwest::Client::new().post(format!("https://{host}/"))
        .header("Content-Type", "application/json; charset=utf-8").header("Host", &host).header("Authorization", authorization)
        .header("X-TC-Action", action).header("X-TC-Version", version).header("X-TC-Timestamp", timestamp.to_string())
        .body(body).timeout(std::time::Duration::from_secs(25));
    if let Some(region) = region.filter(|value| !value.is_empty()) { request = request.header("X-TC-Region", region); }
    let response = match request.send().await {
        Ok(response) => response,
        Err(error) => { let message = format!("腾讯云请求失败: {error}"); crate::write_api_log(access_key_id, &host, action, &payload, None, "失败", Some(&message)); return Err(message); }
    };
    let status = response.status();
    let data: Value = match response.json().await {
        Ok(data) => data,
        Err(error) => { let message = format!("腾讯云返回解析失败: {error}"); crate::write_api_log(access_key_id, &host, action, &payload, None, "失败", Some(&message)); return Err(message); }
    };
    if !status.is_success() || data.pointer("/Response/Error").is_some() {
        let message = data.pointer("/Response/Error/Message").and_then(Value::as_str).or_else(|| data.pointer("/Response/Error/Code").and_then(Value::as_str)).unwrap_or("腾讯云 API 返回错误");
        crate::write_api_log(access_key_id, &host, action, &payload, Some(&data), "失败", Some(message));
        return Err(message.into());
    }
    crate::write_api_log(access_key_id, &host, action, &payload, Some(&data), "成功", None);
    Ok(data.get("Response").cloned().unwrap_or(Value::Null))
}

fn number(value: Option<&Value>) -> f64 { value.and_then(Value::as_f64).or_else(|| value.and_then(Value::as_i64).map(|value| value as f64)).or_else(|| value.and_then(Value::as_str).and_then(|value| value.parse::<f64>().ok())).unwrap_or(0.0) }
fn security_group_policy(ip_protocol: String, port_range: String, source_cidr_ip: String, description: Option<String>) -> Result<Value, String> {
    let protocol = ip_protocol.trim().to_ascii_lowercase(); let range = port_range.trim().to_string(); let source = source_cidr_ip.trim().to_string();
    if !matches!(protocol.as_str(), "tcp" | "udp" | "icmp" | "gre" | "all") { return Err("不支持的安全组协议".into()); }
    let valid_range = range.split_once('/').and_then(|(start, end)| Some((start.parse::<i32>().ok()?, end.parse::<i32>().ok()?))).is_some_and(|(start, end)| if matches!(protocol.as_str(), "tcp" | "udp") { (start == -1 && end == -1) || (start >= 1 && end >= start && end <= 65535) } else { start == -1 && end == -1 });
    if !valid_range { return Err("端口范围与协议不匹配，请使用 80/80、8000/9000 或 -1/-1".into()); }
    if source.is_empty() || !source.contains('/') { return Err("来源地址必须是 CIDR，例如 0.0.0.0/0".into()); }
    let port = if protocol == "all" { "ALL".into() } else if let Some((start, end)) = range.split_once('/') { if start == end { start.into() } else { format!("{start}-{end}") } } else { range };
    let mut policy = json!({"Action":"ACCEPT","CidrBlock":source,"Port":port,"Protocol":protocol.to_ascii_uppercase()}); if let Some(description) = description.map(|value| value.trim().to_string()).filter(|value| !value.is_empty()) { policy["PolicyDescription"] = json!(description); } Ok(policy)
}
fn security_group_port(value: &Value) -> String { let port = value.as_str().unwrap_or(""); if port.eq_ignore_ascii_case("all") { "-1/-1".into() } else if let Some((start, end)) = port.split_once('-') { format!("{start}/{end}") } else if port.is_empty() { "-1/-1".into() } else { format!("{port}/{port}") } }
fn instance(item: &Value, region: &Value) -> Value { let mut value = item.clone(); if let Value::Object(target) = &mut value { let state = item.get("InstanceState").and_then(Value::as_str).unwrap_or(""); let status = match state.to_uppercase().as_str() { "RUNNING" => "Running", "STOPPED" => "Stopped", _ => state }; let network = item.get("InternetAccessible").unwrap_or(&Value::Null); target.insert("InstanceName".into(), item.get("InstanceName").or_else(|| item.get("InstanceId")).cloned().unwrap_or(json!(""))); target.insert("Status".into(), json!(status)); target.insert("PublicIpAddress".into(), item.get("PublicIpAddresses").cloned().unwrap_or(json!([]))); target.insert("PrivateIpAddress".into(), item.get("PrivateIpAddresses").cloned().unwrap_or(json!([]))); target.insert("Cpu".into(), item.get("CPU").cloned().unwrap_or(json!(0))); target.insert("Memory".into(), item.get("Memory").cloned().unwrap_or(json!(0))); target.insert("InternetMaxBandwidthIn".into(), json!(0)); target.insert("InternetMaxBandwidthOut".into(), network.get("InternetMaxBandwidthOut").cloned().unwrap_or(json!(0))); target.insert("OSName".into(), item.get("OsName").or_else(|| item.get("OsType")).cloned().unwrap_or(json!("-"))); target.insert("CreationTime".into(), item.get("CreatedTime").cloned().unwrap_or(json!(""))); target.insert("ExpiredTime".into(), item.get("ExpiredTime").cloned().unwrap_or(json!(""))); target.insert("_region_id".into(), region.get("Region").cloned().unwrap_or(json!(""))); target.insert("_region_name".into(), region.get("RegionName").or_else(|| region.get("Region")).cloned().unwrap_or(json!(""))); } value }
fn lighthouse(item: &Value, region: &str) -> Value { let mut value = item.clone(); if let Value::Object(target) = &mut value { let state = item.get("InstanceState").or_else(|| item.get("InstanceStatus")).and_then(Value::as_str).unwrap_or(""); let status = match state.to_uppercase().as_str() { "RUNNING" => "Running", "STOPPED" => "Stopped", _ => state }; let ips = item.get("PublicAddresses").or_else(|| item.get("PublicIpAddresses")).cloned().unwrap_or(json!([])); target.insert("InstanceName".into(), item.get("InstanceName").or_else(|| item.get("InstanceId")).cloned().unwrap_or(json!(""))); target.insert("InstanceStatus".into(), json!(status)); target.insert("Status".into(), json!(status)); target.insert("PublicIpAddress".into(), ips.clone()); target.insert("PublicIp".into(), ips.as_array().and_then(|values| values.first()).cloned().unwrap_or(json!(""))); target.insert("ImageName".into(), item.get("BlueprintName").or_else(|| item.get("BlueprintId")).cloned().unwrap_or(json!(""))); target.insert("PlanId".into(), item.get("BundleId").or_else(|| item.get("BundleName")).cloned().unwrap_or(json!(""))); target.insert("ExpiredTime".into(), item.get("ExpiredTime").cloned().unwrap_or(json!(""))); target.insert("_region_id".into(), json!(region)); } value }
fn cdb(item: &Value, region: &str) -> Value { let mut value = item.clone(); if let Value::Object(target) = &mut value { let status = item.get("Status").or_else(|| item.get("DBInstanceStatus")).and_then(Value::as_str).unwrap_or(""); target.insert("DBInstanceId".into(), item.get("InstanceId").or_else(|| item.get("DBInstanceId")).cloned().unwrap_or(json!(""))); target.insert("DBInstanceDescription".into(), item.get("InstanceName").or_else(|| item.get("DBInstanceDescription")).or_else(|| item.get("InstanceId")).cloned().unwrap_or(json!(""))); target.insert("DBInstanceStatus".into(), json!(match status { "1" => "Running", "0" => "Stopped", _ => status })); target.insert("DBInstanceType".into(), item.get("DeviceType").or_else(|| item.get("InstanceType")).cloned().unwrap_or(json!(""))); target.insert("DBInstanceClass".into(), item.get("InstanceType").or_else(|| item.get("Model")).cloned().unwrap_or(json!(""))); target.insert("DBInstanceStorage".into(), item.get("Volume").or_else(|| item.get("Storage")).cloned().unwrap_or(json!(0))); target.insert("ConnectionString".into(), item.get("Vip").or_else(|| item.get("ConnectionString")).cloned().unwrap_or(json!(""))); target.insert("Port".into(), item.get("Vport").or_else(|| item.get("Port")).cloned().unwrap_or(json!(""))); target.insert("DBInstanceNetType".into(), json!(if item.get("ProjectId").is_some() { "私有网络" } else { "-" })); target.insert("Engine".into(), item.get("Engine").cloned().unwrap_or(json!("MySQL"))); target.insert("EngineVersion".into(), item.get("EngineVersion").cloned().unwrap_or(json!(""))); target.insert("CreateTime".into(), item.get("CreateTime").cloned().unwrap_or(json!(""))); target.insert("ExpireTime".into(), item.get("DeadlineTime").or_else(|| item.get("ExpireTime")).cloned().unwrap_or(json!(""))); target.insert("_region_id".into(), json!(region)); } value }
fn redis(item: &Value, region: &str) -> Value { let mut value = item.clone(); if let Value::Object(target) = &mut value { let status = item.get("Status").or_else(|| item.get("InstanceStatus")).and_then(Value::as_str).unwrap_or(""); target.insert("InstanceName".into(), item.get("InstanceName").or_else(|| item.get("InstanceId")).cloned().unwrap_or(json!(""))); target.insert("InstanceStatus".into(), json!(if ["2", "RUNNING", "NORMAL"].contains(&status.to_uppercase().as_str()) { "Normal" } else { status })); target.insert("InstanceType".into(), item.get("Type").or_else(|| item.get("TypeName")).cloned().unwrap_or(json!(""))); target.insert("InstanceClass".into(), item.get("Size").or_else(|| item.get("TypeName")).cloned().unwrap_or(json!(""))); target.insert("Capacity".into(), item.get("Size").or_else(|| item.get("Capacity")).cloned().unwrap_or(json!(0))); target.insert("Bandwidth".into(), item.get("Bandwidth").cloned().unwrap_or(json!(0))); target.insert("Connections".into(), item.get("ClientLimit").or_else(|| item.get("Connections")).cloned().unwrap_or(json!(0))); target.insert("ConnectionDomain".into(), item.get("WanIp").or_else(|| item.get("PrivateIp")).or_else(|| item.get("ConnectionDomain")).cloned().unwrap_or(json!(""))); target.insert("Port".into(), item.get("Port").cloned().unwrap_or(json!(""))); target.insert("EngineVersion".into(), item.get("CurrentRedisVersion").or_else(|| item.get("RedisVersion")).cloned().unwrap_or(json!(""))); target.insert("NetworkType".into(), item.get("NetType").cloned().unwrap_or(json!(""))); target.insert("ChargeType".into(), item.get("BillingMode").cloned().unwrap_or(json!(""))); target.insert("EndTime".into(), item.get("DeadTime").or_else(|| item.get("EndTime")).cloned().unwrap_or(json!(""))); target.insert("ArchitectureType".into(), item.get("Type").cloned().unwrap_or(json!("standard"))); target.insert("_region_id".into(), json!(region)); } value }
fn edge(item: &Value) -> Value { let mut value = item.clone(); if let Value::Object(target) = &mut value { target.insert("SiteId".into(), item.get("ZoneId").or_else(|| item.get("Id")).cloned().unwrap_or(json!(""))); target.insert("SiteName".into(), item.get("ZoneName").or_else(|| item.get("ZoneId")).cloned().unwrap_or(json!(""))); target.insert("DomainName".into(), item.get("ZoneName").cloned().unwrap_or(json!(""))); target.insert("Status".into(), item.get("ActiveStatus").or_else(|| item.get("Status")).cloned().unwrap_or(json!(""))); target.insert("AccessType".into(), item.get("Type").or_else(|| item.get("ZoneType")).cloned().unwrap_or(json!(""))); target.insert("Coverage".into(), item.get("Area").or_else(|| item.get("PlanType")).cloned().unwrap_or(json!(""))); target.insert("PlanName".into(), item.get("PlanType").or_else(|| item.get("Plan")).cloned().unwrap_or(json!(""))); } value }
fn registered(item: &Value) -> Value { let mut value = item.clone(); if let Value::Object(target) = &mut value { target.insert("DomainName".into(), item.get("DomainName").or_else(|| item.get("Name")).cloned().unwrap_or(json!(""))); target.insert("RegistrationDate".into(), item.get("RegistrationDate").or_else(|| item.get("CreationDate")).or_else(|| item.get("CreatedOn")).cloned().unwrap_or(json!(""))); target.insert("ExpirationDate".into(), item.get("ExpirationDate").or_else(|| item.get("ExpiredDate")).cloned().unwrap_or(json!(""))); target.insert("RegistrantOrganization".into(), item.get("RegistrantOrganization").or_else(|| item.get("RegistrantName")).cloned().unwrap_or(json!(""))); target.insert("DomainAuditStatus".into(), item.get("RealNameAuditStatus").or_else(|| item.get("DomainAuditStatus")).cloned().unwrap_or(json!(""))); target.insert("DomainStatus".into(), item.get("Status").cloned().unwrap_or(json!(""))); target.insert("DnsServers".into(), item.get("DnsList").or_else(|| item.get("NameServerSet")).cloned().unwrap_or(json!([]))); } value }
fn dnspod(item: &Value) -> Value { let mut value = item.clone(); if let Value::Object(target) = &mut value { target.insert("DomainName".into(), item.get("Name").or_else(|| item.get("DomainName")).cloned().unwrap_or(json!(""))); target.insert("RecordCount".into(), json!(number(item.get("RecordCount")))); target.insert("VersionCode".into(), item.get("Grade").or_else(|| item.get("GradeTitle")).cloned().unwrap_or(json!(""))); target.insert("CreateTime".into(), item.get("CreatedOn").or_else(|| item.get("CreatedAt")).cloned().unwrap_or(json!(""))); target.insert("DomainStatus".into(), item.get("Status").cloned().unwrap_or(json!(""))); target.insert("DnsServers".into(), item.get("NameServers").cloned().unwrap_or(json!([]))); target.insert("DnsSource".into(), json!("DNSPod")); } value }
async fn paged(service: &str, version: &str, action: &str, payload: Value, path: &[&str], region: Option<&str>, access_key_id: &str, access_key_secret: &str) -> Result<Vec<Value>, String> { let mut items = Vec::new(); for offset in (0..10_000).step_by(100) { let mut params = payload.clone(); params.as_object_mut().ok_or("腾讯云分页请求参数无效")?.insert("Offset".into(), json!(offset)); params.as_object_mut().unwrap().insert("Limit".into(), json!(100)); let data = request(service, version, action, params, region, access_key_id, access_key_secret).await?; let page = crate::array_at(&data, path).into_iter().cloned().collect::<Vec<_>>(); let total = number(data.get("TotalCount").or_else(|| data.pointer("/DomainCountInfo/AllTotal")).or_else(|| data.pointer("/DomainCountInfo/TotalCount"))) as usize; let count = page.len(); items.extend(page); if count == 0 || count < 100 || (total > 0 && items.len() >= total) { break; } } Ok(items) }

pub(crate) async fn resource_items(id: i64, resource_type: &str, access_key_id: &str, access_key_secret: &str) -> ResourceResponse {
    let mut items = Vec::new(); let mut errors = Vec::new(); let now = Utc::now().timestamp_millis();
    if !matches!(crate::account_cloud_type(id).as_deref(), Ok("tencent")) { let error = "当前账号不是腾讯云账号".to_string(); return ResourceResponse { resource_type: resource_type.into(), items, errors: vec![error], fetched_at: now }; }
    match resource_type {
        "ecs" => match request("cvm", "2017-03-12", "DescribeRegions", json!({}), None, access_key_id, access_key_secret).await { Ok(data) => for region in crate::array_at(&data, &["RegionSet"]) { if !region.get("RegionState").and_then(Value::as_str).unwrap_or("AVAILABLE").eq_ignore_ascii_case("AVAILABLE") { continue; } let region_id = region.get("Region").and_then(Value::as_str).unwrap_or(""); match paged("cvm", "2017-03-12", "DescribeInstances", json!({}), &["InstanceSet"], Some(region_id), access_key_id, access_key_secret).await { Ok(values) => items.extend(values.iter().map(|item| instance(item, region))), Err(error) => errors.push(format!("{}: {error}", if region_id.is_empty() { "未知地域" } else { region_id })) } }, Err(error) => errors.push(error) },
        "domain" => { let registration = paged("domain", "2018-08-08", "DescribeDomainNameList", json!({}), &["DomainSet"], None, access_key_id, access_key_secret).await; let dns = paged("dnspod", "2021-03-23", "DescribeDomainList", json!({}), &["DomainList"], None, access_key_id, access_key_secret).await; let mut merged = BTreeMap::new(); match registration { Ok(values) => for item in values { let domain = registered(&item); if let Some(name) = domain.get("DomainName").and_then(Value::as_str).filter(|name| !name.is_empty()) { merged.insert(name.to_lowercase(), domain); } }, Err(error) => errors.push(format!("域名注册: {error}")) } match dns { Ok(values) => for item in values { let domain = dnspod(&item); if let Some(name) = domain.get("DomainName").and_then(Value::as_str).filter(|name| !name.is_empty()) { let entry = merged.entry(name.to_lowercase()).or_insert_with(|| json!({"DomainName": name})); if let (Value::Object(target), Value::Object(source)) = (entry, domain) { for (key, value) in source { target.insert(key, value); } } } }, Err(error) => errors.push(format!("DNSPod: {error}")) } items.extend(merged.into_values()); },
        "swas" => { let fallback = match crate::account_region_id(id) { Ok(value) => value, Err(error) => { errors.push(error); String::from("ap-guangzhou") } }; let mut regions = vec![fallback.clone()]; match request("lighthouse", "2020-03-24", "DescribeRegions", json!({}), None, access_key_id, access_key_secret).await { Ok(data) => { regions = crate::array_at(&data, &["RegionSet"]).into_iter().filter(|region| region.get("RegionState").and_then(Value::as_str).unwrap_or("AVAILABLE").eq_ignore_ascii_case("AVAILABLE")).filter_map(|region| region.get("Region").and_then(Value::as_str).filter(|value| !value.is_empty()).map(String::from)).collect(); regions.sort(); regions.dedup(); }, Err(error) => errors.push(format!("读取轻量服务器地域失败，已仅查询 {fallback}: {error}")) } for region in regions { match paged("lighthouse", "2020-03-24", "DescribeInstances", json!({}), &["InstanceSet"], Some(&region), access_key_id, access_key_secret).await { Ok(values) => items.extend(values.iter().map(|item| lighthouse(item, &region))), Err(error) => errors.push(format!("{region}: {error}")) } } },
        "rds" | "redis" => match request("cvm", "2017-03-12", "DescribeRegions", json!({}), None, access_key_id, access_key_secret).await { Ok(data) => for region in crate::array_at(&data, &["RegionSet"]).into_iter().filter(|region| region.get("RegionState").and_then(Value::as_str).unwrap_or("AVAILABLE").eq_ignore_ascii_case("AVAILABLE")).filter_map(|region| region.get("Region").and_then(Value::as_str).map(String::from)) { let (service, version, action, path) = if resource_type == "rds" { ("cdb", "2017-03-20", "DescribeDBInstances", &["Items"][..]) } else { ("redis", "2018-04-12", "DescribeInstances", &["InstanceSet"][..]) }; match paged(service, version, action, json!({}), path, Some(&region), access_key_id, access_key_secret).await { Ok(values) => items.extend(values.iter().map(|item| if resource_type == "rds" { cdb(item, &region) } else { redis(item, &region) })), Err(error) => errors.push(format!("{region}: {error}")) } }, Err(error) => errors.push(error) },
        "oss" => match buckets(access_key_id, access_key_secret).await { Ok(values) => items.extend(values), Err(error) => errors.push(error) },
        "esa" => match paged("teo", "2022-09-01", "DescribeZones", json!({}), &["Zones"], None, access_key_id, access_key_secret).await { Ok(values) => items.extend(values.iter().map(edge)), Err(error) => errors.push(error) },
        other => errors.push(format!("腾讯云暂未接入 {other} 资源")),
    }
    ResourceResponse { resource_type: resource_type.into(), items, errors, fetched_at: now }
}

pub(crate) async fn list_security_groups(id: i64, region_id: &str, instance_id: &str, security_group_id: Option<String>) -> Result<Value, String> {
    if region_id.is_empty() || instance_id.is_empty() { return Err("缺少服务器地域或实例 ID".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?;
    let instance_data = request("cvm", "2017-03-12", "DescribeInstances", json!({"InstanceIds":[instance_id]}), Some(region_id), &access_key_id, &access_key_secret).await?;
    let attached = crate::array_at(&instance_data, &["InstanceSet"]).first().map(|instance| crate::array_at(instance, &["SecurityGroupIds"]).into_iter().filter_map(Value::as_str).map(String::from).collect::<Vec<_>>()).unwrap_or_default();
    let groups_data = request("cvm", "2017-03-12", "DescribeSecurityGroups", json!({"Limit":100}), Some(region_id), &access_key_id, &access_key_secret).await?;
    let groups = crate::array_at(&groups_data, &["SecurityGroupSet"]).into_iter().map(|group| json!({"SecurityGroupId":group.get("SecurityGroupId").cloned().unwrap_or(json!("")),"SecurityGroupName":group.get("SecurityGroupName").cloned().unwrap_or(json!("")),"Description":group.get("SecurityGroupDesc").cloned().unwrap_or(json!("")),"VpcId":group.get("VpcId").cloned().unwrap_or(json!("")),"NicType":""})).filter(|group| attached.is_empty() || group.get("SecurityGroupId").and_then(Value::as_str).is_some_and(|value| attached.iter().any(|id| id == value))).collect::<Vec<_>>();
    let selected = security_group_id.filter(|value| groups.iter().any(|group| group.get("SecurityGroupId").and_then(Value::as_str) == Some(value.as_str()))).or_else(|| groups.first().and_then(|group| group.get("SecurityGroupId")).and_then(Value::as_str).map(String::from)).unwrap_or_default();
    let rules = if selected.is_empty() { Vec::new() } else { let policies = request("cvm", "2017-03-12", "DescribeSecurityGroupPolicies", json!({"SecurityGroupId":selected}), Some(region_id), &access_key_id, &access_key_secret).await?; crate::array_at(&policies, &["SecurityGroupPolicySet","Ingress"]).into_iter().map(|rule| json!({"Direction":"ingress","IpProtocol":rule.get("Protocol").and_then(Value::as_str).unwrap_or("").to_ascii_lowercase(),"PortRange":security_group_port(rule.get("Port").unwrap_or(&Value::Null)),"SourceCidrIp":rule.get("CidrBlock").cloned().unwrap_or(json!("")),"SourceGroupId":rule.get("SecurityGroupId").cloned().unwrap_or(json!("")),"Policy":rule.get("Action").cloned().unwrap_or(json!("ACCEPT")),"Priority":rule.get("PolicyIndex").cloned().unwrap_or(json!(0)),"Description":rule.get("PolicyDescription").cloned().unwrap_or(json!("")),"NicType":""})).collect() };
    Ok(json!({"groups":groups,"selectedSecurityGroupId":selected,"rules":rules}))
}

pub(crate) async fn authorize_security_group_rule(id: i64, region_id: &str, security_group_id: &str, ip_protocol: String, port_range: String, source_cidr_ip: String, description: Option<String>) -> Result<String, String> {
    if region_id.is_empty() || security_group_id.is_empty() { return Err("缺少安全组地域或安全组 ID".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let result = request("cvm", "2017-03-12", "AuthorizeSecurityGroupIngress", json!({"SecurityGroupId":security_group_id,"SecurityGroupPolicySet":[security_group_policy(ip_protocol, port_range, source_cidr_ip, description)?]}), Some(region_id), &access_key_id, &access_key_secret).await?; Ok(result.get("RequestId").and_then(Value::as_str).unwrap_or_default().to_string())
}

pub(crate) async fn revoke_security_group_rule(id: i64, region_id: &str, security_group_id: &str, priority: i32) -> Result<String, String> {
    if region_id.is_empty() || security_group_id.is_empty() || priority < 0 { return Err("缺少安全组地域、安全组 ID 或规则索引".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let result = request("cvm", "2017-03-12", "RevokeSecurityGroupIngress", json!({"SecurityGroupId":security_group_id,"SecurityGroupPolicySet":[{"PolicyIndex":priority}]}), Some(region_id), &access_key_id, &access_key_secret).await?; Ok(result.get("RequestId").and_then(Value::as_str).unwrap_or_default().to_string())
}

pub(crate) async fn rename_instance(id: i64, region_id: &str, instance_id: &str, instance_name: &str) -> Result<String, String> {
    if !matches!(crate::account_cloud_type(id).as_deref(), Ok("tencent")) { return Err("当前账号不是腾讯云账号".into()); }
    if region_id.trim().is_empty() || instance_id.trim().is_empty() { return Err("缺少服务器地域或实例 ID".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let data = request("cvm", "2017-03-12", "ModifyInstancesAttribute", json!({"InstanceIds":[instance_id],"InstanceName":instance_name}), Some(region_id), &access_key_id, &access_key_secret).await?;
    Ok(data.get("RequestId").and_then(Value::as_str).unwrap_or_default().to_string())
}

pub(crate) async fn swas_instance_action(id: i64, region_id: &str, instance_id: &str, action: &str, force_stop: bool) -> Result<Value, String> {
    if !matches!(crate::account_cloud_type(id).as_deref(), Ok("tencent")) { return Err("当前账号不是腾讯云账号".into()); }
    let action_name = match action { "start" => "StartInstances", "reboot" => "RebootInstances", "stop" => "StopInstances", _ => return Err("不支持的轻量服务器操作".into()) };
    let mut payload = json!({"InstanceIds":[instance_id]}); if action == "reboot" && force_stop { payload["ForceStop"] = json!(true); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?;
    request("lighthouse", "2020-03-24", action_name, payload, Some(region_id), &access_key_id, &access_key_secret).await
}

pub(crate) async fn cvm_instance_reboot(id: i64, region_id: &str, instance_id: &str, force_stop: bool) -> Result<String, String> {
    if crate::account_cloud_type(id)? != "tencent" { return Err("当前账号不是腾讯云账号".into()); } if region_id.is_empty() || instance_id.is_empty() { return Err("缺少服务器地域或实例 ID".into()); } let mut payload = json!({"InstanceIds": [instance_id]}); if force_stop { payload["ForceStop"] = json!(true); } let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let result = request("cvm", "2017-03-12", "RebootInstances", payload, Some(region_id), &access_key_id, &access_key_secret).await?; Ok(result.get("RequestId").and_then(Value::as_str).unwrap_or_default().to_string())
}

pub(crate) async fn cvm_instance_action(id: i64, region_id: &str, instance_id: &str, action: &str, force_stop: bool) -> Result<String, String> {
    if crate::account_cloud_type(id)? != "tencent" { return Err("当前账号不是腾讯云账号".into()); } if region_id.is_empty() || instance_id.is_empty() { return Err("缺少服务器地域或实例 ID".into()); } let action_name = match action { "start" => "StartInstances", "stop" => "StopInstances", "reboot" => "RebootInstances", _ => return Err("不支持的腾讯云服务器操作".into()) }; let mut payload = json!({"InstanceIds": [instance_id]}); if force_stop && (action == "stop" || action == "reboot") { payload["ForceStop"] = json!(true); } let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let result = request("cvm", "2017-03-12", action_name, payload, Some(region_id), &access_key_id, &access_key_secret).await?; Ok(result.get("RequestId").and_then(Value::as_str).unwrap_or_default().to_string())
}

fn lighthouse_port(port: &str) -> String { let port = port.trim(); if port.eq_ignore_ascii_case("all") { return "-1/-1".into(); } let parts = port.split('-').collect::<Vec<_>>(); if parts.len() == 2 { format!("{}/{}", parts[0], parts[1]) } else { format!("{port}/{port}") } }

pub(crate) async fn list_light_firewall_rules(id: i64, region_id: &str, instance_id: &str) -> Result<Value, String> {
    if crate::account_cloud_type(id)? != "tencent" { return Err("当前账号不是腾讯云账号".into()); } let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let result = request("lighthouse", "2020-03-24", "DescribeFirewallRules", json!({"InstanceId": instance_id, "Limit": 100}), Some(region_id), &access_key_id, &access_key_secret).await?; let rules = crate::array_at(&result, &["FirewallRuleSet"]).into_iter().filter(|rule| rule.get("Action").and_then(Value::as_str).unwrap_or("ACCEPT").eq_ignore_ascii_case("ACCEPT")).map(|rule| { let firewall_rule = json!({"Protocol": rule.get("Protocol").cloned().unwrap_or(json!("")), "Port": rule.get("Port").cloned().unwrap_or(json!("")), "CidrBlock": rule.get("CidrBlock").cloned().unwrap_or(json!("")), "Action": rule.get("Action").cloned().unwrap_or(json!("ACCEPT")), "FirewallRuleDescription": rule.get("FirewallRuleDescription").cloned().unwrap_or(json!(""))}); json!({"RuleId": "", "IpProtocol": rule.get("Protocol").cloned().unwrap_or(json!("")), "PortRange": lighthouse_port(rule.get("Port").and_then(Value::as_str).unwrap_or("")), "SourceCidrIp": rule.get("CidrBlock").cloned().unwrap_or(json!("")), "Policy": rule.get("Action").cloned().unwrap_or(json!("ACCEPT")), "Description": rule.get("FirewallRuleDescription").cloned().unwrap_or(json!("")), "FirewallRule": firewall_rule}) }).collect::<Vec<_>>(); Ok(json!({"rules": rules, "firewallVersion": result.get("FirewallVersion").cloned().unwrap_or(Value::Null)}))
}

pub(crate) async fn create_light_firewall_rule(id: i64, region_id: &str, instance_id: &str, protocol: &str, port_range: &str, source: &str, description: &str, firewall_version: Option<i64>) -> Result<Value, String> {
    if crate::account_cloud_type(id)? != "tencent" { return Err("当前账号不是腾讯云账号".into()); } let parts = port_range.split('/').collect::<Vec<_>>(); let port = if parts[0] == parts[1] { parts[0].to_string() } else { format!("{}-{}", parts[0], parts[1]) }; let mut rule = json!({"Protocol": protocol.to_ascii_uppercase(), "Port": port, "CidrBlock": source, "Action": "ACCEPT"}); if !description.is_empty() { rule["FirewallRuleDescription"] = json!(description); } let mut payload = json!({"InstanceId": instance_id, "FirewallRules": [rule]}); if let Some(version) = firewall_version { payload["FirewallVersion"] = json!(version); } let (access_key_id, access_key_secret) = crate::account_credentials(id)?; request("lighthouse", "2020-03-24", "CreateFirewallRules", payload, Some(region_id), &access_key_id, &access_key_secret).await
}

pub(crate) async fn delete_light_firewall_rule(id: i64, region_id: &str, instance_id: &str, firewall_rule: Value, firewall_version: Option<i64>) -> Result<Value, String> {
    if crate::account_cloud_type(id)? != "tencent" { return Err("当前账号不是腾讯云账号".into()); } let mut payload = json!({"InstanceId": instance_id, "FirewallRules": [firewall_rule]}); if let Some(version) = firewall_version { payload["FirewallVersion"] = json!(version); } let (access_key_id, access_key_secret) = crate::account_credentials(id)?; request("lighthouse", "2020-03-24", "DeleteFirewallRules", payload, Some(region_id), &access_key_id, &access_key_secret).await
}

pub(crate) async fn finance_summary(id: i64) -> (Value, Value, Value) {
    if crate::account_cloud_type(id).as_deref() != Ok("tencent") { return (json!({}), json!({}), json!({})); }
    let Ok((access_key_id, access_key_secret)) = crate::account_credentials(id) else { return (json!({}), json!({}), json!({})); }; let billing_cycle = Utc::now().format("%Y-%m").to_string(); let (identity, balance, bill) = tokio::join!(request("cam", "2019-01-16", "GetUserAppId", json!({}), None, &access_key_id, &access_key_secret), request("billing", "2018-07-09", "DescribeAccountBalance", json!({}), None, &access_key_id, &access_key_secret), request("billing", "2018-07-09", "DescribeBillSummaryByPayMode", json!({"BeginTime": format!("{billing_cycle}-01"), "EndTime": Utc::now().format("%Y-%m-%d").to_string()}), None, &access_key_id, &access_key_secret)); (identity.unwrap_or_else(|_| json!({})), balance.unwrap_or_else(|_| json!({})), bill.unwrap_or_else(|_| json!({})))
}

pub(crate) async fn instance_disks(id: i64, region_id: &str, instance_id: &str) -> Result<Vec<Value>, String> {
    if crate::account_cloud_type(id)? != "tencent" { return Err("当前账号不是腾讯云账号".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?;
    let result = request("cbs", "2017-03-12", "DescribeDisks", serde_json::json!({"InstanceId": instance_id}), Some(region_id), &access_key_id, &access_key_secret).await?;
    Ok(crate::array_at(&result, &["DiskSet"]).into_iter().map(|disk| serde_json::json!({"DiskId": disk.get("DiskId").cloned().unwrap_or(serde_json::json!("")), "DiskName": disk.get("DiskName").or_else(|| disk.get("DiskId")).cloned().unwrap_or(serde_json::json!("")), "Category": disk.get("DiskType").cloned().unwrap_or(serde_json::json!("")), "Size": disk.get("DiskSize").cloned().unwrap_or(serde_json::json!(0)), "Status": disk.get("DiskState").cloned().unwrap_or(serde_json::json!(""))})).collect())
}

pub(crate) async fn list_rds_databases(id: i64, region_id: &str, instance_id: &str) -> Result<Vec<Value>, String> {
    if crate::account_cloud_type(id)? != "tencent" { return Err("当前账号不是腾讯云账号".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let data = request("cdb", "2017-03-20", "DescribeDatabases", serde_json::json!({"InstanceId": instance_id}), Some(region_id), &access_key_id, &access_key_secret).await?;
    Ok(crate::array_at(&data, &["Items"]).into_iter().map(|item| { let mut value = (*item).clone(); if let Value::Object(ref mut target) = value { target.insert("DBName".into(), item.get("DatabaseName").or_else(|| item.get("DBName")).cloned().unwrap_or(serde_json::json!(""))); } value }).collect())
}

pub(crate) async fn list_rds_accounts(id: i64, region_id: &str, instance_id: &str) -> Result<Vec<Value>, String> {
    if crate::account_cloud_type(id)? != "tencent" { return Err("当前账号不是腾讯云账号".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let data = request("cdb", "2017-03-20", "DescribeAccounts", serde_json::json!({"InstanceId": instance_id}), Some(region_id), &access_key_id, &access_key_secret).await?;
    Ok(crate::array_at(&data, &["Items"]).into_iter().map(|item| serde_json::json!({"AccountName": item.get("AccountName").or_else(|| item.get("UserName")).cloned().unwrap_or(serde_json::json!("")), "AccountType": item.get("AccountType").cloned().unwrap_or(serde_json::json!("Normal")), "AccountStatus": item.get("Status").cloned().unwrap_or(serde_json::json!("Available")), "AccountDescription": item.get("Description").cloned().unwrap_or(serde_json::json!(""))})).collect())
}

pub(crate) async fn list_redis_accounts(id: i64, instance_id: &str, region_id: &str) -> Result<Vec<Value>, String> {
    if crate::account_cloud_type(id)? != "tencent" { return Err("当前账号不是腾讯云账号".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let data = request("redis", "2018-04-12", "DescribeInstanceAccount", serde_json::json!({"InstanceId": instance_id}), Some(region_id), &access_key_id, &access_key_secret).await?;
    Ok(crate::array_at(&data, &["Accounts"]).into_iter().map(|item| serde_json::json!({"AccountName": item.get("AccountName").or_else(|| item.get("UserName")).cloned().unwrap_or(serde_json::json!("")), "AccountType": item.get("AccountType").cloned().unwrap_or(serde_json::json!("Normal")), "AccountStatus": item.get("Status").cloned().unwrap_or(serde_json::json!("Available")), "AccountDescription": item.get("Description").cloned().unwrap_or(serde_json::json!(""))})).collect())
}

pub(crate) async fn list_dns_records(id: i64, domain: &str, record_type: Option<String>, keyword: Option<String>) -> Result<Value, String> {
    if crate::account_cloud_type(id)? != "tencent" { return Err("当前账号不是腾讯云账号".into()); } let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let mut payload = serde_json::Map::new(); payload.insert("Domain".into(), serde_json::json!(domain)); if let Some(value) = record_type.filter(|value| !value.is_empty()) { payload.insert("RecordType".into(), serde_json::json!(value)); } if let Some(value) = keyword.filter(|value| !value.is_empty()) { payload.insert("Value".into(), serde_json::json!(value)); } let result = request("dnspod", "2021-03-23", "DescribeRecordList", Value::Object(payload), None, &access_key_id, &access_key_secret).await?; let items = crate::array_at(&result, &["RecordList"]).into_iter().map(|item| serde_json::json!({"RecordId": item.get("RecordId").cloned().unwrap_or(serde_json::json!("")), "Type": item.get("Type").cloned().unwrap_or(serde_json::json!("")), "RR": item.get("Name").or_else(|| item.get("RR")).cloned().unwrap_or(serde_json::json!("")), "Value": item.get("Value").cloned().unwrap_or(serde_json::json!("")), "TTL": item.get("TTL").cloned().unwrap_or(serde_json::json!("")), "MX": item.get("MX").cloned().unwrap_or(serde_json::json!("")), "Line": item.get("Line").cloned().unwrap_or(serde_json::json!("")), "Status": item.get("Status").cloned().unwrap_or(serde_json::json!(""))})).collect::<Vec<_>>(); Ok(serde_json::json!({"items": items, "total": result.pointer("/RecordCountInfo/TotalCount").cloned().or_else(|| result.get("TotalCount").cloned()).unwrap_or(serde_json::json!(0))}))
}

fn cos_authorization_with_query(access_key_id: &str, access_key_secret: &str, host: &str, query: &str) -> Result<String, String> {
    let start = Utc::now().timestamp() - 1; let sign_time = format!("{start};{}", start + 900); let canonical_query = query.split('&').filter(|item| !item.is_empty()).collect::<Vec<_>>().join("&"); let canonical_request = format!("get\n/\n{canonical_query}\n\nhost={host}\n"); let mut key_mac: Hmac<Sha1> = <Hmac<Sha1> as Mac>::new_from_slice(access_key_secret.as_bytes()).map_err(|error| error.to_string())?; key_mac.update(sign_time.as_bytes()); let sign_key = hex::encode(key_mac.finalize().into_bytes()); let string_to_sign = format!("sha1\n{sign_time}\n{:x}\n", Sha1::digest(canonical_request.as_bytes())); let mut sign_mac: Hmac<Sha1> = <Hmac<Sha1> as Mac>::new_from_slice(sign_key.as_bytes()).map_err(|error| error.to_string())?; sign_mac.update(string_to_sign.as_bytes()); Ok(format!("q-sign-algorithm=sha1&q-ak={}&q-sign-time={sign_time}&q-key-time={sign_time}&q-header-list=host&q-url-param-list={}&q-signature={}", crate::rpc_encode(access_key_id), query.split('&').filter_map(|item| item.split_once('=').map(|(key, _)| key)).collect::<Vec<_>>().join(";"), hex::encode(sign_mac.finalize().into_bytes())))
}

pub(crate) async fn list_objects(id: i64, bucket: &str, location: &str, prefix: &str, marker: &str) -> Result<Value, String> {
    if crate::account_cloud_type(id)? != "tencent" { return Err("当前账号不是腾讯云账号".into()); }
    let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let mut query = "list-type=2&max-keys=1000&delimiter=%2F".to_string(); if !prefix.is_empty() { query.push_str(&format!("&prefix={}", crate::rpc_encode(prefix))); } if !marker.is_empty() { query.push_str(&format!("&continuation-token={}", crate::rpc_encode(marker))); } let host = format!("{bucket}.cos.{location}.myqcloud.com"); let authorization = cos_authorization_with_query(&access_key_id, &access_key_secret, &host, &query)?; let response = reqwest::Client::new().get(format!("https://{host}/?{query}")).header("Host", &host).header("Authorization", authorization).timeout(std::time::Duration::from_secs(25)).send().await.map_err(|error| format!("COS 请求失败: {error}"))?; let status = response.status(); let body = response.text().await.map_err(|error| error.to_string())?; if !status.is_success() { let message = xml_text(&body, "Message"); return Err(format!("COS 返回错误（{status}）：{}", if message.is_empty() { "请求被拒绝" } else { &message })); } let objects = xml_blocks(&body, "Contents").into_iter().map(|object| json!({"Key": xml_text(&object, "Key"), "Size": xml_text(&object, "Size"), "LastModified": xml_text(&object, "LastModified"), "ETag": xml_text(&object, "ETag")})).filter(|object| object.get("Key").and_then(Value::as_str).is_some_and(|key| !key.is_empty() && key != prefix)).collect::<Vec<_>>(); Ok(json!({"objects": objects, "prefixes": xml_blocks(&body, "CommonPrefixes").into_iter().map(|entry| xml_text(&entry, "Prefix")).filter(|value| !value.is_empty()).collect::<Vec<_>>(), "isTruncated": xml_text(&body, "IsTruncated").eq_ignore_ascii_case("true"), "nextMarker": xml_text(&body, "NextContinuationToken")}))
}

pub(crate) async fn get_acl(id: i64, bucket: &str, location: &str) -> Result<String, String> {
    if crate::account_cloud_type(id)? != "tencent" { return Err("当前账号不是腾讯云账号".into()); } let (access_key_id, access_key_secret) = crate::account_credentials(id)?; let host = format!("{bucket}.cos.{location}.myqcloud.com"); let authorization = cos_authorization_with_query(&access_key_id, &access_key_secret, &host, "acl")?; let response = reqwest::Client::new().get(format!("https://{host}/?acl")).header("Host", &host).header("Authorization", authorization).timeout(std::time::Duration::from_secs(25)).send().await.map_err(|error| format!("COS 请求失败: {error}"))?; let status = response.status(); let body = response.text().await.map_err(|error| error.to_string())?; if !status.is_success() { return Err(format!("COS 返回错误（{status}）：{}", xml_text(&body, "Code"))); } Ok(xml_text(&body, "Permission"))
}
